"""Curated word bank for crossword generation.

Contains common English words (3-8 letters) with simple clues,
optimized for dense crossword packing.
"""

from __future__ import annotations

# (word, clue) — organized by length for easy lookup
_RAW: list[tuple[str, str]] = [
    # ── 3-letter words ─────────────────────────────────
    ("ACE", "Top card"), ("ACT", "Stage performance"), ("ADD", "Sum up"),
    ("AGE", "Number of years"), ("AID", "Help out"), ("AIM", "Point at"),
    ("AIR", "What we breathe"), ("ALE", "Pub drink"), ("ANT", "Tiny insect"),
    ("APE", "Gorilla, e.g."), ("ARC", "Curved line"), ("ARE", "Exist (plural)"),
    ("ARK", "Noah's vessel"), ("ARM", "Body limb"), ("ART", "Museum display"),
    ("ATE", "Had a meal"), ("AWE", "Amazement"), ("AXE", "Chopping tool"),
    ("BAD", "Not good"), ("BAG", "Shopping carrier"), ("BAN", "Prohibit"),
    ("BAR", "Pub counter"), ("BAT", "Baseball stick"), ("BED", "Sleep spot"),
    ("BET", "Wager"), ("BIG", "Large"), ("BIT", "Small piece"),
    ("BOW", "Ribbon shape"), ("BOX", "Cardboard container"), ("BOY", "Young male"),
    ("BUD", "Flower beginning"), ("BUG", "Insect"), ("BUS", "Transit vehicle"),
    ("BUY", "Purchase"), ("CAB", "Taxi"), ("CAN", "Tin container"),
    ("CAP", "Head covering"), ("CAR", "Automobile"), ("CAT", "Feline pet"),
    ("COP", "Police officer"), ("COT", "Small bed"), ("COW", "Farm animal"),
    ("CRY", "Shed tears"), ("CUB", "Bear baby"), ("CUP", "Drinking vessel"),
    ("CUT", "Slice"), ("DAD", "Father"), ("DAM", "River barrier"),
    ("DAY", "24 hours"), ("DEN", "Animal's lair"), ("DEW", "Morning moisture"),
    ("DIG", "Excavate"), ("DIM", "Not bright"), ("DIP", "Quick swim"),
    ("DOC", "Doctor, briefly"), ("DOG", "Man's best friend"), ("DOT", "Small spot"),
    ("DRY", "Not wet"), ("DUE", "Owed"), ("DYE", "Color changer"),
    ("EAR", "Hearing organ"), ("EAT", "Consume food"), ("EEL", "Snake-like fish"),
    ("EGG", "Breakfast item"), ("ELF", "Santa's helper"), ("ELK", "Large deer"),
    ("ELM", "Shade tree"), ("EMU", "Australian bird"), ("END", "Finish"),
    ("ERA", "Time period"), ("EVE", "Night before"), ("EWE", "Female sheep"),
    ("EYE", "Sight organ"), ("FAN", "Cooling device"), ("FAR", "Distant"),
    ("FAT", "Not thin"), ("FED", "Gave food"), ("FEE", "Charge"),
    ("FEW", "Not many"), ("FIG", "Sweet fruit"), ("FIN", "Fish flipper"),
    ("FIT", "In good shape"), ("FIX", "Repair"), ("FLY", "Soar through air"),
    ("FOE", "Enemy"), ("FOG", "Thick mist"), ("FOR", "In favor of"),
    ("FOX", "Cunning animal"), ("FRY", "Cook in oil"), ("FUN", "Good time"),
    ("FUR", "Animal coat"), ("GAP", "Opening"), ("GAS", "Fuel"),
    ("GEM", "Precious stone"), ("GIN", "Cocktail spirit"), ("GNU", "African animal"),
    ("GOD", "Supreme being"), ("GUM", "Chewing candy"), ("GUN", "Weapon"),
    ("GUT", "Stomach area"), ("GUY", "Fellow"), ("GYM", "Exercise place"),
    ("HAD", "Possessed"), ("HAM", "Pork cut"), ("HAT", "Head topper"),
    ("HAY", "Dried grass"), ("HEN", "Female chicken"), ("HER", "She, objective"),
    ("HID", "Concealed"), ("HIM", "He, objective"), ("HIP", "Trendy"),
    ("HIT", "Strike"), ("HOG", "Greedy one"), ("HOP", "Small jump"),
    ("HOT", "Very warm"), ("HOW", "In what way"), ("HUB", "Center point"),
    ("HUE", "Color shade"), ("HUG", "Embrace"), ("HUT", "Small shelter"),
    ("ICE", "Frozen water"), ("ICY", "Cold and slippery"), ("ILL", "Sick"),
    ("IMP", "Little devil"), ("INK", "Pen fluid"), ("INN", "Small hotel"),
    ("ION", "Charged atom"), ("IRE", "Anger"), ("IVY", "Climbing plant"),
    ("JAB", "Quick punch"), ("JAM", "Fruit spread"), ("JAR", "Glass container"),
    ("JAW", "Mouth bone"), ("JAY", "Blue bird"), ("JET", "Fast plane"),
    ("JOB", "Employment"), ("JOG", "Slow run"), ("JOT", "Write quickly"),
    ("JOY", "Happiness"), ("JUG", "Pouring vessel"), ("KEG", "Beer barrel"),
    ("KEY", "Lock opener"), ("KID", "Young child"), ("KIN", "Relatives"),
    ("KIT", "Tool set"), ("LAB", "Science room"), ("LAD", "Young fellow"),
    ("LAP", "One circuit"), ("LAW", "Legal rule"), ("LAY", "Put down"),
    ("LED", "Guided"), ("LEG", "Walking limb"), ("LET", "Allow"),
    ("LID", "Cover on top"), ("LIE", "Untruth"), ("LIP", "Mouth edge"),
    ("LIT", "Illuminated"), ("LOG", "Tree trunk piece"), ("LOT", "Great amount"),
    ("LOW", "Not high"), ("MAD", "Angry"), ("MAN", "Adult male"),
    ("MAP", "Road guide"), ("MAT", "Floor covering"), ("MAY", "Spring month"),
    ("MEN", "Males"), ("MET", "Encountered"), ("MIX", "Blend together"),
    ("MOB", "Angry crowd"), ("MOM", "Mother"), ("MOP", "Floor cleaner"),
    ("MUD", "Wet earth"), ("MUG", "Coffee cup"), ("NAP", "Short sleep"),
    ("NET", "Fishing mesh"), ("NEW", "Not old"), ("NIT", "Hair pest"),
    ("NOD", "Head gesture"), ("NOR", "And not"), ("NOT", "Negative"),
    ("NOW", "At this time"), ("NUN", "Convent dweller"), ("NUT", "Hard-shell snack"),
    ("OAK", "Sturdy tree"), ("OAR", "Rowing blade"), ("OAT", "Cereal grain"),
    ("ODD", "Strange"), ("ODE", "Lyric poem"), ("OIL", "Lubricant"),
    ("OLD", "Not young"), ("ONE", "Single"), ("OPT", "Choose"),
    ("ORB", "Sphere"), ("ORE", "Metal source"), ("OUR", "Belonging to us"),
    ("OUT", "Not in"), ("OWE", "Be in debt"), ("OWL", "Night bird"),
    ("OWN", "Possess"), ("PAD", "Writing tablet"), ("PAN", "Cooking vessel"),
    ("PAT", "Gentle touch"), ("PAW", "Animal foot"), ("PAY", "Compensation"),
    ("PEA", "Green veggie"), ("PEG", "Wall hook"), ("PEN", "Writing tool"),
    ("PET", "Companion animal"), ("PIE", "Baked dessert"), ("PIG", "Farm animal"),
    ("PIN", "Sharp fastener"), ("PIT", "Deep hole"), ("PLY", "Layer"),
    ("POD", "Pea holder"), ("POP", "Soda"), ("POT", "Cooking vessel"),
    ("PUB", "British bar"), ("PUN", "Play on words"), ("PUP", "Young dog"),
    ("PUT", "Place"), ("RAG", "Torn cloth"), ("RAM", "Male sheep"),
    ("RAN", "Sprinted"), ("RAP", "Knock sharply"), ("RAT", "Rodent"),
    ("RAW", "Uncooked"), ("RAY", "Beam of light"), ("RED", "Stop light color"),
    ("RIB", "Chest bone"), ("RID", "Free from"), ("RIG", "Set up"),
    ("RIM", "Edge of a cup"), ("RIP", "Tear apart"), ("ROB", "Steal from"),
    ("ROD", "Fishing pole"), ("ROT", "Decay"), ("ROW", "Table line"),
    ("RUB", "Massage"), ("RUG", "Floor carpet"), ("RUM", "Pirate's drink"),
    ("RUN", "Sprint"), ("RUT", "Deep track"), ("RYE", "Bread grain"),
    ("SAD", "Unhappy"), ("SAP", "Tree juice"), ("SAT", "Was seated"),
    ("SAW", "Cutting tool"), ("SAY", "Speak"), ("SEA", "Ocean"),
    ("SET", "Put in place"), ("SEW", "Stitch"), ("SHE", "Female pronoun"),
    ("SHY", "Timid"), ("SIN", "Wrongdoing"), ("SIP", "Drink slowly"),
    ("SIR", "Polite address"), ("SIS", "Sister, briefly"), ("SIT", "Take a seat"),
    ("SIX", "Half a dozen"), ("SKI", "Snow sport"), ("SKY", "Above us"),
    ("SLY", "Crafty"), ("SOB", "Weep loudly"), ("SOD", "Turf"),
    ("SON", "Male child"), ("SPA", "Relaxation spot"), ("SPY", "Secret agent"),
    ("STY", "Pig pen"), ("SUB", "Submarine"), ("SUM", "Total"),
    ("SUN", "Daytime star"), ("TAB", "Bar bill"), ("TAG", "Price label"),
    ("TAN", "Sun-kissed"), ("TAP", "Faucet"), ("TAR", "Road coating"),
    ("TAX", "Government levy"), ("TEA", "Hot beverage"), ("TEN", "Decade count"),
    ("THE", "Common article"), ("TIE", "Neck accessory"), ("TIN", "Metal can"),
    ("TIP", "Gratuity"), ("TOE", "Foot digit"), ("TON", "2000 pounds"),
    ("TOO", "Also"), ("TOP", "Highest point"), ("TOW", "Pull along"),
    ("TOY", "Child's plaything"), ("TUB", "Bathing vessel"), ("TUG", "Pull hard"),
    ("TWO", "Pair count"), ("URN", "Ash holder"), ("USE", "Employ"),
    ("VAN", "Cargo vehicle"), ("VAT", "Large tank"), ("VET", "Animal doctor"),
    ("VIA", "By way of"), ("VIE", "Compete"), ("VOW", "Solemn promise"),
    ("WAR", "Armed conflict"), ("WAX", "Candle material"), ("WAY", "Path"),
    ("WEB", "Spider's creation"), ("WED", "Marry"), ("WET", "Not dry"),
    ("WIG", "Fake hair"), ("WIN", "Triumph"), ("WIT", "Cleverness"),
    ("WOE", "Great sorrow"), ("WOK", "Asian pan"), ("WON", "Was victorious"),
    ("WOO", "Court romantically"), ("YAK", "Shaggy ox"), ("YAM", "Sweet potato"),
    ("YAP", "Bark shrilly"), ("YEA", "Affirmative vote"), ("YES", "Affirmative"),
    ("YET", "Still"), ("YEW", "Evergreen tree"), ("ZAP", "Zap with a laser"),
    ("ZEN", "Peaceful state"), ("ZIP", "Zipper action"), ("ZOO", "Animal park"),
    # ── 3-letter crossword fill ──
    ("ADO", "Fuss"), ("AGA", "Turkish commander"), ("AHA", "Eureka!"),
    ("AKA", "Also known as"), ("ALL", "Everything"), ("AMI", "Friend, in French"),
    ("AMP", "Electrical unit"), ("ANI", "Tropical bird"), ("ANY", "Some"),
    ("ASP", "Venomous snake"), ("AVE", "Roman greeting"), ("AWL", "Leather tool"),
    ("BAA", "Sheep sound"), ("BAH", "Humbug!"), ("BRA", "Undergarment"),
    ("CHI", "Greek letter"), ("CUE", "Actor's prompt"), ("DAB", "Light touch"),
    ("DOE", "Female deer"), ("EBB", "Recede"), ("ECU", "Old French coin"),
    ("EEK", "Mouse sighting cry"), ("EKE", "Barely manage"),
    ("EME", "Uncle, in Spanish"), ("ENS", "Naval officer"),
    ("EON", "Long time span"), ("ERE", "Before, poetically"),
    ("ERG", "Energy unit"), ("ERR", "Make a mistake"), ("ESS", "S-shaped curve"),
    ("ETA", "Arrival guess"), ("GAL", "Young woman"),
    ("GEL", "Hair product"), ("GET", "Obtain"), ("HIE", "Hurry along"),
    ("IRK", "Annoy"), ("LEA", "Meadow"), ("LEE", "Sheltered side"),
    ("LEI", "Hawaiian garland"), ("NEE", "Born as"), ("NTH", "To the ___ degree"),
    ("OCA", "Wood sorrel plant"), ("OHO", "Surprise exclamation"),
    ("OVA", "Eggs, biologically"), ("PAP", "Soft food"), ("PHI", "Greek letter"),
    ("PRO", "Expert"), ("PSI", "Greek letter"), ("PST", "Hey, over here!"),
    ("RHO", "Greek letter"), ("ROE", "Fish eggs"), ("RUE", "Regret deeply"),
    ("TAO", "Eastern philosophy"), ("TAU", "Greek letter"),
    ("TOR", "Rocky peak"), ("TRY", "Attempt"), ("UDO", "Japanese plant"),
    ("UKE", "Small guitar, briefly"), ("UTE", "Western tribe"),
    ("WHO", "Question word"),
    ("YEN", "Strong desire"), ("THY", "Your, old-style"), ("AGO", "In the past"),
    ("AUK", "Arctic seabird"), ("DON", "Put on"),
    ("DUO", "Twosome"), ("EGO", "Self-image"), ("FRO", "To and ___"),
    ("GAB", "Chat"), ("HEW", "Chop"), ("NAB", "Catch"), ("NAG", "Pester"),
    ("OAF", "Clumsy one"), ("OLE", "Bullfight cheer"),
    ("PAL", "Buddy"), ("PEW", "Church seat"),
    ("POI", "Hawaiian dish"), ("RIA", "Narrow inlet"), ("SRI", "Asian title"),
    ("FOP", "Dandy"), ("LYE", "Soap ingredient"), ("AYE", "Affirmative vote"),
    ("MRS", "Married woman's title"), ("APT", "Fitting"), ("ASH", "Fireplace residue"),
    ("AWN", "Bristle-like extension"), ("SOL", "Musical note"),
    ("NON", "Not (prefix)"), ("OBI", "Japanese sash"),
    # ── more 3-letter crossword fill ──
    ("AFT", "Toward the stern"), ("ALP", "Mountain peak"), ("ALT", "High note"),
    ("ASS", "Donkey"), ("DIS", "Show disrespect"), ("EFT", "Young newt"),
    ("GOO", "Sticky stuff"), ("HAW", "Hesitation sound"), ("IDE", "Fish type"),
    ("NAE", "No, in Scotland"), ("PER", "For each"), ("RAD", "Cool, slangily"),
    ("RAH", "Cheer"), ("REV", "Engine sound"), ("SOP", "Soak up"),
    ("TAV", "Hebrew letter"), ("THO", "Though, archaic"), ("WEE", "Tiny"),
    ("WHY", "Question word"), ("WRY", "Dry-humored"), ("QUA", "In the role of"),
    ("RET", "Soak flax"), ("BEL", "Sound unit"), ("PED", "Foot: prefix"),
    ("NEB", "Beak"), ("LEK", "Albanian currency"), ("SER", "Eastern title"),
    ("ADE", "Fruit drink suffix"),

    # ── 4-letter words ─────────────────────────────────
    ("ABLE", "Capable"), ("ACHE", "Dull pain"), ("ACID", "Sour substance"),
    ("ACRE", "Land measure"), ("AGED", "Old"), ("AIDE", "Assistant"),
    ("ARCH", "Curved structure"), ("AREA", "Region"), ("ARMY", "Military force"),
    ("ARTS", "Creative field"), ("ASIA", "Largest continent"), ("AXLE", "Wheel rod"),
    ("BABE", "Infant"), ("BACK", "Rear side"), ("BAIT", "Fish lure"),
    ("BAKE", "Oven cook"), ("BALD", "Hairless"), ("BALE", "Hay bundle"),
    ("BALL", "Round toy"), ("BAND", "Music group"), ("BANK", "Money keeper"),
    ("BARE", "Uncovered"), ("BARK", "Dog sound"), ("BARN", "Farm building"),
    ("BASE", "Foundation"), ("BATH", "Tub soak"), ("BEAM", "Light ray"),
    ("BEAN", "Lima or kidney"), ("BEAR", "Forest animal"), ("BEAT", "Rhythm"),
    ("BEEF", "Steak source"), ("BEER", "Hops drink"), ("BELL", "Ringing device"),
    ("BELT", "Waist band"), ("BEND", "Curve"), ("BEST", "Number one"),
    ("BIKE", "Two-wheeler"), ("BILL", "Invoice"), ("BIND", "Tie together"),
    ("BIRD", "Feathered flyer"), ("BITE", "Chomp"), ("BLOW", "Wind gust"),
    ("BLUE", "Sky color"), ("BLUR", "Make fuzzy"), ("BOAT", "Water vessel"),
    ("BODY", "Physical form"), ("BOLD", "Daring"), ("BOLT", "Lightning flash"),
    ("BOMB", "Explosive"), ("BOND", "Connection"), ("BONE", "Skeleton part"),
    ("BOOK", "Reading material"), ("BOOT", "Footwear"), ("BORE", "Drill"),
    ("BORN", "Came into the world"), ("BOSS", "Manager"), ("BOTH", "The two"),
    ("BOWL", "Cereal dish"), ("BROW", "Forehead"), ("BULB", "Light source"),
    ("BULK", "Large quantity"), ("BULL", "Male bovine"), ("BUMP", "Small collision"),
    ("BURN", "Fire damage"), ("BUST", "Sculpture head"), ("BUZZ", "Bee sound"),
    ("CAFE", "Coffee shop"), ("CAGE", "Animal enclosure"), ("CAKE", "Birthday treat"),
    ("CALF", "Young cow"), ("CALL", "Phone ring"), ("CALM", "Peaceful"),
    ("CAME", "Arrived"), ("CAMP", "Tent site"), ("CAPE", "Hero's garment"),
    ("CARD", "Greeting item"), ("CARE", "Concern"), ("CART", "Shopping vehicle"),
    ("CASE", "Suitcase"), ("CASH", "Paper money"), ("CAST", "Throw"),
    ("CAVE", "Underground room"), ("CHAT", "Casual talk"), ("CHEF", "Master cook"),
    ("CHIP", "Potato snack"), ("CHOP", "Cut roughly"), ("CITY", "Urban area"),
    ("CLAM", "Shell creature"), ("CLAP", "Hand sound"), ("CLAY", "Pottery material"),
    ("CLIP", "Paper holder"), ("CLUE", "Puzzle hint"), ("COAL", "Black fuel"),
    ("COAT", "Warm jacket"), ("CODE", "Secret message"), ("COIL", "Spiral"),
    ("COIN", "Pocket change"), ("COLD", "Not warm"), ("COLE", "Slaw veggie"),
    ("COLT", "Young horse"), ("COMB", "Hair tool"), ("COME", "Arrive"),
    ("COOK", "Prepare food"), ("COOL", "Slightly cold"), ("COPE", "Deal with"),
    ("COPY", "Duplicate"), ("CORD", "Thick string"), ("CORE", "Apple center"),
    ("CORK", "Bottle stopper"), ("CORN", "Cob veggie"), ("COST", "Price"),
    ("COZY", "Snug"), ("CRAB", "Beach creature"), ("CREW", "Ship workers"),
    ("CROP", "Farm harvest"), ("CROW", "Black bird"), ("CUBE", "Six-sided shape"),
    ("CURB", "Street edge"), ("CURE", "Remedy"), ("CURL", "Hair ringlet"),
    ("DARE", "Challenge"), ("DARK", "Without light"), ("DART", "Pub game"),
    ("DASH", "Quick run"), ("DATA", "Information"), ("DATE", "Calendar day"),
    ("DAWN", "Sunrise time"), ("DEAL", "Bargain"), ("DEAR", "Beloved"),
    ("DECK", "Ship floor"), ("DEED", "Legal document"), ("DEEM", "Consider"),
    ("DEEP", "Not shallow"), ("DEER", "Forest animal"), ("DENY", "Refuse"),
    ("DESK", "Office table"), ("DIAL", "Phone feature"), ("DICE", "Game cubes"),
    ("DIET", "Eating plan"), ("DIME", "Ten cents"), ("DINE", "Eat out"),
    ("DIRT", "Soil"), ("DISC", "Round plate"), ("DISH", "Plate"),
    ("DOCK", "Boat parking"), ("DOES", "Performs"), ("DOME", "Rounded roof"),
    ("DONE", "Finished"), ("DOOM", "Dreadful fate"), ("DOOR", "Room entrance"),
    ("DOSE", "Medicine amount"), ("DOVE", "Peace bird"), ("DOWN", "Opposite of up"),
    ("DOZE", "Light nap"), ("DRIP", "Leak slowly"), ("DROP", "Fall"),
    ("DRUM", "Beat instrument"), ("DUAL", "Double"), ("DUCK", "Pond bird"),
    ("DUEL", "Two-person fight"), ("DULL", "Boring"), ("DUMP", "Trash site"),
    ("DUNE", "Sand hill"), ("DUSK", "Twilight"), ("DUST", "Fine particles"),
    ("DUTY", "Obligation"), ("EACH", "Every one"), ("EARN", "Make money"),
    ("EASE", "Comfort"), ("EAST", "Sunrise direction"), ("EASY", "Not hard"),
    ("EDGE", "Border"), ("EDIT", "Revise"), ("ELSE", "Otherwise"),
    ("EMIT", "Give off"), ("ENDS", "Finishes"), ("EPIC", "Grand tale"),
    ("EVEN", "Level"), ("EVIL", "Wicked"), ("EXAM", "School test"),
    ("EXIT", "Way out"), ("FACE", "Front of head"), ("FACT", "Truth"),
    ("FADE", "Lose color"), ("FAIL", "Not succeed"), ("FAIR", "Just"),
    ("FAKE", "Not real"), ("FALL", "Autumn"), ("FAME", "Celebrity"),
    ("FANG", "Vampire tooth"), ("FARE", "Bus price"), ("FARM", "Rural land"),
    ("FAST", "Quick"), ("FATE", "Destiny"), ("FAWN", "Young deer"),
    ("FEAR", "Fright"), ("FEAT", "Achievement"), ("FEED", "Give food"),
    ("FEEL", "Touch"), ("FEET", "Plural of foot"), ("FELL", "Dropped"),
    ("FELT", "Past of feel"), ("FEND", "Ward off"), ("FERN", "Leafy plant"),
    ("FILE", "Document holder"), ("FILL", "Make full"), ("FILM", "Movie"),
    ("FIND", "Discover"), ("FINE", "Penalty"), ("FIRE", "Flames"),
    ("FIRM", "Company"), ("FISH", "Aquatic creature"), ("FIST", "Clenched hand"),
    ("FLAG", "Country banner"), ("FLAW", "Defect"), ("FLEA", "Dog pest"),
    ("FLED", "Ran away"), ("FLEW", "Past of fly"), ("FLIP", "Turn over"),
    ("FLOG", "Whip"), ("FLOW", "Stream movement"), ("FOAM", "Bubble mass"),
    ("FOIL", "Tin wrap"), ("FOLD", "Crease"), ("FOLK", "People"),
    ("FOND", "Affectionate"), ("FOOD", "Nourishment"), ("FOOL", "Silly person"),
    ("FOOT", "12 inches"), ("FORD", "River crossing"), ("FORK", "Eating utensil"),
    ("FORM", "Shape"), ("FORT", "Military post"), ("FOUL", "Unfair play"),
    ("FOUR", "After three"), ("FREE", "No cost"), ("FROM", "Starting point"),
    ("FUEL", "Energy source"), ("FULL", "Not empty"), ("FUME", "Toxic vapor"),
    ("FUND", "Money supply"), ("FUSE", "Safety device"), ("FURY", "Rage"),
    ("GAIN", "Profit"), ("GALE", "Strong wind"), ("GAME", "Sport"),
    ("GANG", "Group of thugs"), ("GAPE", "Stare open-mouthed"), ("GARB", "Clothing"),
    ("GATE", "Fence opening"), ("GAVE", "Donated"), ("GAZE", "Stare"),
    ("GEAR", "Equipment"), ("GIFT", "Present"), ("GIST", "Main point"),
    ("GIVE", "Hand over"), ("GLAD", "Happy"), ("GLEN", "Narrow valley"),
    ("GLOW", "Soft light"), ("GLUE", "Adhesive"), ("GNAW", "Chew persistently"),
    ("GOAL", "Aim"), ("GOAT", "Bearded animal"), ("GOES", "Travels"),
    ("GOLD", "Precious metal"), ("GOLF", "Club sport"), ("GONE", "Departed"),
    ("GOOD", "Not bad"), ("GRAB", "Seize"), ("GRAY", "Neutral color"),
    ("GREW", "Got bigger"), ("GRID", "Crisscross pattern"), ("GRIN", "Wide smile"),
    ("GRIP", "Hold tightly"), ("GRIT", "Determination"), ("GROW", "Get larger"),
    ("GULF", "Large bay"), ("GUST", "Wind burst"), ("GUTS", "Courage"),
    ("HAIL", "Ice pellets"), ("HAIR", "Head covering"), ("HALE", "Healthy"),
    ("HALF", "50 percent"), ("HALL", "Corridor"), ("HALT", "Stop"),
    ("HAND", "Five fingers"), ("HANG", "Suspend"), ("HARE", "Fast rabbit"),
    ("HARM", "Damage"), ("HARP", "Stringed instrument"), ("HATE", "Detest"),
    ("HAUL", "Drag"), ("HAVE", "Possess"), ("HAZE", "Thin fog"),
    ("HAZY", "Not clear"), ("HEAD", "Body top"), ("HEAL", "Mend"),
    ("HEAP", "Pile"), ("HEAR", "Listen"), ("HEAT", "Warmth"),
    ("HEED", "Pay attention"), ("HEEL", "Foot back"), ("HELD", "Kept"),
    ("HELP", "Assist"), ("HERB", "Cooking plant"), ("HERD", "Cattle group"),
    ("HERE", "This place"), ("HERO", "Brave one"), ("HIDE", "Conceal"),
    ("HIGH", "Tall"), ("HIKE", "Nature walk"), ("HILL", "Small mountain"),
    ("HILT", "Sword handle"), ("HINT", "Subtle clue"), ("HIRE", "Employ"),
    ("HOLD", "Grip"), ("HOLE", "Opening"), ("HOME", "Residence"),
    ("HONE", "Sharpen"), ("HOOD", "Head cover"), ("HOOK", "Curved metal"),
    ("HOPE", "Optimism"), ("HORN", "Brass instrument"), ("HOSE", "Garden tube"),
    ("HOST", "Party giver"), ("HOUR", "60 minutes"), ("HUGE", "Enormous"),
    ("HULL", "Ship body"), ("HUNG", "Suspended"), ("HUNT", "Search for prey"),
    ("HYMN", "Church song"), ("ICON", "Symbol"), ("IDEA", "Thought"),
    ("IDLE", "Inactive"), ("INCH", "Small measure"), ("INTO", "Inside"),
    ("IRON", "Press clothes"), ("ISLE", "Small island"), ("ITEM", "Object"),
    ("JADE", "Green stone"), ("JAIL", "Prison"), ("JAZZ", "Music genre"),
    ("JEAN", "Denim fabric"), ("JEER", "Mock"), ("JEST", "Joke"),
    ("JOBS", "Occupations"), ("JOIN", "Connect"), ("JOKE", "Funny story"),
    ("JURY", "Trial panel"), ("JUST", "Fair"), ("KEEN", "Eager"),
    ("KEEP", "Retain"), ("KELP", "Seaweed"), ("KEPT", "Held on to"),
    ("KICK", "Foot strike"), ("KILL", "End life"), ("KIND", "Generous"),
    ("KING", "Royal ruler"), ("KISS", "Peck"), ("KITE", "Flying toy"),
    ("KNOB", "Door handle"), ("KNOT", "Tie"), ("KNOW", "Be aware"),
    ("LACE", "Delicate fabric"), ("LACK", "Shortage"), ("LAME", "Weak excuse"),
    ("LAMP", "Light source"), ("LAND", "Terra firma"), ("LANE", "Narrow road"),
    ("LARD", "Cooking fat"), ("LARK", "Songbird"), ("LAST", "Final"),
    ("LATE", "Not on time"), ("LAWN", "Grass yard"), ("LEAD", "Guide"),
    ("LEAF", "Tree green"), ("LEAK", "Drip"), ("LEAN", "Thin"),
    ("LEAP", "Jump high"), ("LEFT", "Not right"), ("LEND", "Loan"),
    ("LENS", "Camera part"), ("LESS", "Not as much"), ("LIAR", "Fibber"),
    ("LICK", "Tongue action"), ("LIFE", "Existence"), ("LIFT", "Raise up"),
    ("LIKE", "Enjoy"), ("LIMB", "Tree branch"), ("LIME", "Green citrus"),
    ("LIMP", "Hobble"), ("LINE", "Queue"), ("LINK", "Chain part"),
    ("LINT", "Fabric fuzz"), ("LION", "King of jungle"), ("LIST", "Inventory"),
    ("LIVE", "Be alive"), ("LOAD", "Cargo"), ("LOAF", "Bread unit"),
    ("LOAN", "Lending"), ("LOCK", "Door fastener"), ("LOFT", "Upper room"),
    ("LOGO", "Brand symbol"), ("LONE", "Solitary"), ("LONG", "Not short"),
    ("LOOK", "See"), ("LOOP", "Circular shape"), ("LORD", "Nobleman"),
    ("LORE", "Traditional knowledge"), ("LOSE", "Not win"), ("LOSS", "Defeat"),
    ("LOST", "Not found"), ("LOUD", "High volume"), ("LOVE", "Deep affection"),
    ("LUCK", "Good fortune"), ("LUMP", "Bump"), ("LURE", "Tempt"),
    ("LURK", "Hide in wait"), ("LUSH", "Verdant"), ("MACE", "Medieval weapon"),
    ("MADE", "Created"), ("MAID", "House cleaner"), ("MAIL", "Post"),
    ("MAIN", "Primary"), ("MAKE", "Create"), ("MALE", "Man"),
    ("MALL", "Shopping center"), ("MALT", "Brewery grain"), ("MANE", "Lion's hair"),
    ("MANY", "Lots of"), ("MARE", "Female horse"), ("MARK", "Stain"),
    ("MART", "Market"), ("MASH", "Crush"), ("MASK", "Face cover"),
    ("MASS", "Large amount"), ("MAST", "Ship pole"), ("MATE", "Partner"),
    ("MAZE", "Puzzle path"), ("MEAL", "Dinner"), ("MEAN", "Unkind"),
    ("MEAT", "Protein food"), ("MEET", "Encounter"), ("MELD", "Blend"),
    ("MELT", "Thaw"), ("MEMO", "Office note"), ("MEND", "Repair"),
    ("MENU", "Food list"), ("MERE", "Only"), ("MESH", "Interlocking net"),
    ("MICE", "Plural of mouse"), ("MILD", "Gentle"), ("MILE", "5280 feet"),
    ("MILK", "Dairy drink"), ("MILL", "Grain grinder"), ("MIME", "Silent actor"),
    ("MIND", "Brain"), ("MINE", "Belongs to me"), ("MINT", "Fresh herb"),
    ("MISS", "Fail to hit"), ("MIST", "Light fog"), ("MOAN", "Groan"),
    ("MOAT", "Castle trench"), ("MODE", "Setting"), ("MOLD", "Fungi"),
    ("MOLE", "Burrowing animal"), ("MOOD", "Emotional state"), ("MOON", "Night light"),
    ("MOOR", "Boggy land"), ("MOPE", "Sulk"), ("MORE", "Additional"),
    ("MOSS", "Green ground cover"), ("MOST", "Maximum"), ("MOTH", "Night flyer"),
    ("MOVE", "Change position"), ("MUCH", "A lot"), ("MULE", "Donkey hybrid"),
    ("MUSE", "Ponder"), ("MUST", "Have to"), ("MYTH", "Legend"),
    ("NAIL", "Hammer target"), ("NAME", "What you're called"), ("NAVY", "Sea force"),
    ("NEAR", "Close by"), ("NEAT", "Tidy"), ("NECK", "Below the head"),
    ("NEED", "Require"), ("NEST", "Bird's home"), ("NEWS", "Current events"),
    ("NEXT", "Following"), ("NICE", "Pleasant"), ("NINE", "After eight"),
    ("NODE", "Connection point"), ("NONE", "Zero"), ("NOON", "Midday"),
    ("NORM", "Standard"), ("NOSE", "Smell organ"), ("NOTE", "Short message"),
    ("NOUN", "Person, place, thing"), ("NUMB", "Without feeling"), ("OBEY", "Follow orders"),
    ("ODDS", "Probability"), ("ODOR", "Smell"), ("OGRE", "Fairy tale villain"),
    ("OINK", "Pig sound"), ("OMEN", "Sign"), ("ONCE", "One time"),
    ("ONLY", "Sole"), ("ONTO", "On top of"), ("OOZE", "Seep slowly"),
    ("OPEN", "Not closed"), ("ORAL", "Spoken"), ("ORCA", "Killer whale"),
    ("OVEN", "Baking device"), ("OVER", "Above"), ("PACE", "Walking speed"),
    ("PACK", "Bundle"), ("PAGE", "Book leaf"), ("PAID", "Compensated"),
    ("PAIL", "Bucket"), ("PAIN", "Hurt"), ("PAIR", "Two of a kind"),
    ("PALE", "Light-colored"), ("PALM", "Hand center"), ("PANE", "Window glass"),
    ("PARK", "Green space"), ("PART", "Piece"), ("PASS", "Go by"),
    ("PAST", "Previous"), ("PATH", "Trail"), ("PEAK", "Mountain top"),
    ("PEAL", "Bell ring"), ("PEAR", "Green fruit"), ("PEAT", "Soil type"),
    ("PEEL", "Banana skin"), ("PEER", "Equal"), ("PELT", "Animal skin"),
    ("PEST", "Nuisance"), ("PICK", "Choose"), ("PIER", "Dock"),
    ("PILE", "Stack"), ("PILL", "Medicine tablet"), ("PINE", "Evergreen tree"),
    ("PIPE", "Tube"), ("PLAN", "Strategy"), ("PLAY", "Have fun"),
    ("PLEA", "Appeal"), ("PLOD", "Walk heavily"), ("PLOT", "Story line"),
    ("PLOW", "Farm tool"), ("PLOY", "Trick"), ("PLUG", "Electrical connector"),
    ("PLUM", "Purple fruit"), ("PLUS", "Addition sign"), ("POEM", "Verse"),
    ("POET", "Verse writer"), ("POKE", "Prod"), ("POLE", "Long stick"),
    ("POLL", "Survey"), ("POLO", "Horse sport"), ("POND", "Small lake"),
    ("POOL", "Swimming spot"), ("POOR", "Not wealthy"), ("POPE", "Vatican leader"),
    ("PORK", "Pig meat"), ("PORT", "Harbor"), ("POSE", "Model stance"),
    ("POST", "Mail item"), ("POUR", "Flow"), ("PRAY", "Worship"),
    ("PREY", "Hunted animal"), ("PROP", "Stage support"), ("PROS", "Advantages"),
    ("PULL", "Tug"), ("PULP", "Soft mass"), ("PUMP", "Inflate"),
    ("PURE", "Uncontaminated"), ("PUSH", "Shove"), ("QUIZ", "Quick test"),
    ("RACE", "Speed contest"), ("RACK", "Storage shelf"), ("RAFT", "Water float"),
    ("RAGE", "Fury"), ("RAID", "Surprise attack"), ("RAIL", "Fence bar"),
    ("RAIN", "Wet weather"), ("RAKE", "Leaf tool"), ("RAMP", "Incline"),
    ("RANG", "Phone sound"), ("RANK", "Position"), ("RARE", "Uncommon"),
    ("RASH", "Skin irritation"), ("RATE", "Speed"), ("RAVE", "Rant"),
    ("READ", "Peruse"), ("REAL", "Genuine"), ("REAP", "Harvest"),
    ("REAR", "Back end"), ("REED", "Marsh grass"), ("REEF", "Coral structure"),
    ("REEL", "Film spool"), ("RENT", "Monthly payment"), ("REST", "Relax"),
    ("RICE", "Asian grain"), ("RICH", "Wealthy"), ("RIDE", "Go by horse"),
    ("RIND", "Cheese outer"), ("RING", "Phone sound"), ("RIPE", "Ready to eat"),
    ("RISE", "Go up"), ("RISK", "Danger"), ("ROAD", "Highway"),
    ("ROAM", "Wander"), ("ROBE", "Lounging garment"), ("ROCK", "Stone"),
    ("RODE", "Past of ride"), ("ROLE", "Part to play"), ("ROLL", "Bread piece"),
    ("ROOF", "House top"), ("ROOM", "Living space"), ("ROOT", "Plant base"),
    ("ROPE", "Thick cord"), ("ROSE", "Red flower"), ("ROSY", "Pink"),
    ("RUDE", "Impolite"), ("RUIN", "Destroy"), ("RULE", "Regulation"),
    ("RUNG", "Ladder step"), ("RUSH", "Hurry"), ("RUST", "Iron corrosion"),
    ("SACK", "Large bag"), ("SAFE", "Secure"), ("SAGE", "Wise one"),
    ("SAID", "Spoke"), ("SAIL", "Boat canvas"), ("SAKE", "Purpose"),
    ("SALE", "Discount event"), ("SALT", "Table seasoning"), ("SAME", "Identical"),
    ("SAND", "Beach grains"), ("SANE", "Rational"), ("SANG", "Past of sing"),
    ("SANK", "Went under"), ("SAVE", "Rescue"), ("SCAN", "Look over"),
    ("SCAR", "Wound mark"), ("SEAL", "Wax stamp"), ("SEAM", "Stitch line"),
    ("SEED", "Plant starter"), ("SEEK", "Search for"), ("SEEM", "Appear"),
    ("SEEN", "Viewed"), ("SELF", "Oneself"), ("SELL", "Vend"),
    ("SEND", "Mail out"), ("SHED", "Garden building"), ("SHIN", "Lower leg"),
    ("SHIP", "Ocean vessel"), ("SHOP", "Store"), ("SHOW", "Display"),
    ("SHUT", "Close"), ("SICK", "Unwell"), ("SIDE", "Flank"),
    ("SIGH", "Deep breath"), ("SIGN", "Notice"), ("SILK", "Smooth fabric"),
    ("SILO", "Grain tower"), ("SINK", "Kitchen basin"), ("SIRE", "Father"),
    ("SITE", "Location"), ("SIZE", "Dimensions"), ("SKIM", "Read quickly"),
    ("SKIN", "Body covering"), ("SKIP", "Hop along"), ("SKIT", "Short play"),
    ("SLAB", "Thick slice"), ("SLAM", "Shut hard"), ("SLAP", "Face strike"),
    ("SLED", "Snow vehicle"), ("SLID", "Past of slide"), ("SLIM", "Thin"),
    ("SLIP", "Slide"), ("SLIT", "Narrow cut"), ("SLOT", "Coin opening"),
    ("SLOW", "Not fast"), ("SLUG", "Garden pest"), ("SMOG", "Dirty air"),
    ("SNAP", "Break sharply"), ("SNIP", "Small cut"), ("SNOW", "Winter flakes"),
    ("SNUB", "Slight"), ("SOAP", "Cleaning bar"), ("SOAR", "Fly high"),
    ("SOCK", "Foot garment"), ("SODA", "Fizzy drink"), ("SOFA", "Couch"),
    ("SOFT", "Not hard"), ("SOIL", "Earth"), ("SOLD", "Past of sell"),
    ("SOLE", "Only one"), ("SOME", "A few"), ("SONG", "Musical piece"),
    ("SOON", "Shortly"), ("SOOT", "Chimney residue"), ("SORE", "Tender"),
    ("SORT", "Arrange"), ("SOUL", "Spirit"), ("SOUP", "Liquid meal"),
    ("SOUR", "Tart"), ("SPAN", "Bridge length"), ("SPAR", "Boxing match"),
    ("SPIN", "Rotate"), ("SPIT", "Expel"), ("SPOT", "Location"),
    ("SPUR", "Motivate"), ("STAB", "Pierce"), ("STAR", "Night twinkler"),
    ("STAY", "Remain"), ("STEM", "Flower stalk"), ("STEP", "Stair part"),
    ("STEW", "Slow-cooked dish"), ("STIR", "Mix"), ("STOP", "Halt"),
    ("STUB", "Ticket part"), ("STUN", "Shock"), ("SUCH", "Of that kind"),
    ("SUIT", "Business attire"), ("SULK", "Pout"), ("SURE", "Certain"),
    ("SURF", "Ride waves"), ("SWAN", "Elegant bird"), ("SWAP", "Trade"),
    ("SWIM", "Pool activity"), ("TACK", "Small nail"), ("TAIL", "Animal rear"),
    ("TAKE", "Grab"), ("TALE", "Story"), ("TALK", "Speak"),
    ("TALL", "High"), ("TAME", "Domesticated"), ("TANK", "Water holder"),
    ("TAPE", "Sticky strip"), ("TART", "Small pie"), ("TASK", "Job"),
    ("TEAM", "Group"), ("TEAR", "Rip"), ("TELL", "Inform"),
    ("TEND", "Look after"), ("TENT", "Camping shelter"), ("TERM", "School period"),
    ("TEST", "Exam"), ("TEXT", "Written message"), ("THAN", "Compared to"),
    ("THAT", "Which"), ("THEM", "Those people"), ("THEN", "After that"),
    ("THEY", "Third person plural"), ("THIN", "Slim"), ("THIS", "Here"),
    ("TIDE", "Ocean movement"), ("TIDY", "Neat"), ("TIER", "Level"),
    ("TILE", "Floor square"), ("TILL", "Until"), ("TILT", "Lean"),
    ("TIME", "Clock reading"), ("TINY", "Very small"), ("TIRE", "Car rubber"),
    ("TOAD", "Warty amphibian"), ("TOLL", "Bridge fee"), ("TOMB", "Burial place"),
    ("TONE", "Sound quality"), ("TOOK", "Past of take"), ("TOOL", "Implement"),
    ("TOPS", "Highest"), ("TORE", "Ripped"), ("TORN", "Ripped"),
    ("TOUR", "Guided trip"), ("TOWN", "Small city"), ("TRAP", "Snare"),
    ("TRAY", "Serving plate"), ("TREE", "Tall plant"), ("TREK", "Long journey"),
    ("TRIM", "Cut edges"), ("TRIO", "Group of three"), ("TRIP", "Journey"),
    ("TROT", "Horse gait"), ("TRUE", "Not false"), ("TUBE", "Hollow cylinder"),
    ("TUCK", "Fold in"), ("TUFT", "Clump"), ("TULIP", "Spring flower"),
    ("TUNA", "Sushi fish"), ("TUNE", "Melody"), ("TURN", "Rotate"),
    ("TUSK", "Elephant tooth"), ("TWIN", "Identical sibling"), ("TYPE", "Kind"),
    ("UPON", "On"), ("URGE", "Strong desire"), ("USED", "Not new"),
    ("VAIN", "Conceited"), ("VALE", "Valley"), ("VANE", "Wind indicator"),
    ("VARY", "Differ"), ("VASE", "Flower holder"), ("VAST", "Immense"),
    ("VEIL", "Face covering"), ("VEIN", "Blood vessel"), ("VENT", "Air outlet"),
    ("VERB", "Action word"), ("VERY", "Extremely"), ("VEST", "Sleeveless top"),
    ("VIEW", "Scenery"), ("VINE", "Climbing plant"), ("VOID", "Empty space"),
    ("VOLT", "Electrical unit"), ("VOTE", "Cast ballot"), ("WADE", "Walk in water"),
    ("WAGE", "Salary"), ("WAIL", "Loud cry"), ("WAIT", "Be patient"),
    ("WAKE", "Stop sleeping"), ("WALK", "Stroll"), ("WALL", "Room divider"),
    ("WAND", "Magic stick"), ("WANT", "Desire"), ("WARD", "Hospital section"),
    ("WARM", "Slightly hot"), ("WARN", "Alert"), ("WARP", "Bend out of shape"),
    ("WART", "Skin bump"), ("WASH", "Clean"), ("WASP", "Stinging insect"),
    ("WAVE", "Ocean motion"), ("WEAK", "Not strong"), ("WEAR", "Put on clothes"),
    ("WEED", "Garden invader"), ("WEEK", "Seven days"), ("WELL", "Water source"),
    ("WENT", "Departed"), ("WERE", "Past of are"), ("WEST", "Sunset direction"),
    ("WHAT", "Which thing"), ("WHEN", "At what time"), ("WHIM", "Sudden urge"),
    ("WHIP", "Crack"), ("WHOM", "Objective who"), ("WICK", "Candle string"),
    ("WIDE", "Broad"), ("WIFE", "Spouse"), ("WILD", "Untamed"),
    ("WILL", "Future tense"), ("WILT", "Droop"), ("WILY", "Cunning"),
    ("WIND", "Moving air"), ("WINE", "Grape drink"), ("WING", "Bird's arm"),
    ("WINK", "Eye blink"), ("WIPE", "Clean off"), ("WIRE", "Metal strand"),
    ("WISE", "Smart"), ("WISH", "Hope for"), ("WITH", "Alongside"),
    ("WOKE", "Became alert"), ("WOLF", "Pack animal"), ("WOOD", "Tree material"),
    ("WOOL", "Sheep fiber"), ("WORD", "Vocabulary unit"), ("WORE", "Had on"),
    ("WORK", "Labor"), ("WORM", "Garden crawler"), ("WORN", "Used up"),
    ("WRAP", "Gift cover"), ("WREN", "Small bird"), ("WRIT", "Legal order"),
    ("YANK", "Pull sharply"), ("YARD", "Lawn"), ("YARN", "Knitting thread"),
    ("YEAR", "365 days"), ("YELL", "Shout"), ("YOGA", "Stretching exercise"),
    ("YOKE", "Ox harness"), ("YOUR", "Belonging to you"), ("ZEAL", "Enthusiasm"),
    ("ZERO", "Nothing"), ("ZINC", "Metal element"), ("ZONE", "Area"),
    # ── 4-letter crossword fill ──
    ("ALEE", "Sheltered from wind"), ("ALOE", "Skin soother"),
    ("ANTE", "Poker stake"), ("ARIA", "Opera solo"), ("ATOP", "On top of"),
    ("DRAY", "Heavy cart"), ("DYAD", "Pair"), ("EBON", "Black, poetically"),
    ("EDDO", "Tropical tuber"), ("ERNE", "Sea eagle"), ("EPEE", "Fencing sword"),
    ("IAMB", "Metrical foot"), ("JETE", "Ballet leap"),
    ("LUTE", "Stringed instrument"), ("MEAD", "Honey drink"),
    ("OLEO", "Margarine"), ("STYE", "Eyelid swelling"),
    ("UVEA", "Eye layer"), ("AGEE", "Askew"), ("AHEM", "Throat-clearing sound"),
    ("ANEW", "Once more"), ("AVOW", "Declare openly"),
    ("AWOL", "Absent without leave"),
    ("DEFT", "Skillful"), ("DELI", "Sub shop"), ("ELLS", "Measuring units"),
    ("EMIR", "Arabian prince"),
    ("ETCH", "Engrave"), ("EURO", "Continental currency"),
    ("EWES", "Flock females"), ("EXEC", "Company bigwig"),
    ("GAIT", "Walking style"),
    ("IBIS", "Wading bird"), ("IDOL", "Adored one"),
    ("LAIR", "Dragon's den"), ("LAVA", "Volcanic flow"), ("LEVY", "Tax"),
    ("MESA", "Flat-topped hill"),
    ("NAVE", "Church section"), ("OAST", "Kiln"), ("OGLE", "Stare at"),
    ("OHMS", "Resistance units"), ("OMIT", "Leave out"),
    ("OPAL", "Iridescent gem"), ("ORES", "Mine finds"),
    ("OWED", "Was in debt"), ("PANG", "Sharp pain"), ("PARE", "Peel"),
    ("PYRE", "Funeral fire"), ("RILE", "Irritate"), ("RIME", "Frost"),
    ("RUSE", "Trick"), ("SERF", "Feudal worker"),
    ("SPAS", "Wellness centers"),
    ("TACO", "Mexican fare"), ("TARE", "Weed"), ("TOGA", "Roman garment"),
    ("TRES", "Very, in French"), ("TYKE", "Small child"),
    ("ABET", "Help in crime"), ("ABUT", "Border on"), ("ACME", "Peak"),
    ("ADOS", "Fuss"), ("AJAR", "Slightly open"),
    ("AKIN", "Related"), ("ALES", "Pub drinks"), ("AMID", "In the middle of"),
    ("AMOK", "Out of control"), ("ANTS", "Picnic pests"),
    ("ARCS", "Curved lines"), ("ARES", "Greek war god"),
    ("ARID", "Bone-dry"), ("ASEA", "On the ocean"), ("AUTO", "Car"),
    ("BARD", "Shakespeare, e.g."), ("BIDE", "Wait"),
    ("BIER", "Funeral stand"), ("BILE", "Bitter fluid"),
    ("BOAR", "Wild pig"), ("BRAE", "Hillside"), ("DAIS", "Speaking platform"),
    ("DAZE", "Stun"),
    ("EAVE", "Roof overhang"), ("EDGY", "Nervous"),
    ("EGAD", "Old-time exclamation"), ("ELAN", "Enthusiasm"),
    ("ELMS", "Shade trees"), ("EMUS", "Large flightless birds"),
    ("EONS", "Long time spans"), ("ERAS", "Historical periods"),
    ("ETNA", "Sicilian volcano"),
    ("GURU", "Wise teacher"), ("LEER", "Sly look"),
    ("IRES", "Angers"), ("OAFS", "Clumsy ones"), ("ORBS", "Spheres"),
    ("OPTS", "Chooses"), ("APTS", "Fitting"), ("OBOE", "Woodwind instrument"),
    ("OKRA", "Gumbo veggie"),
    ("OPAH", "Moonfish"), ("OXEN", "Plow pullers"),
    ("PATE", "Top of the head"), ("PRIG", "Snob"),
    ("SPRY", "Nimble"), ("UGLY", "Not attractive"),
    # ── more 4-letter crossword fill ──
    ("AILS", "Troubles"), ("ANOA", "Small buffalo"), ("ARIL", "Seed covering"),
    ("IOTA", "Tiny bit"), ("LEEK", "Onion relative"), ("LIED", "German song"),
    ("OLES", "Bullfight cheers"), ("ETAS", "Greek letters"),
    ("ACES", "Top cards"), ("LATH", "Strip of wood"), ("PLEB", "Common person"),
    ("KAYO", "Knockout, briefly"), ("BAAL", "Semitic deity"),
    ("ANES", "Anesthetics, briefly"),

    # ── 5-letter words ─────────────────────────────────
    ("ABORT", "Cancel mission"), ("ACTOR", "Stage performer"), ("ADMIT", "Confess"),
    ("ADOPT", "Take in"), ("AGILE", "Nimble"), ("AGREE", "See eye to eye"),
    ("ALARM", "Warning sound"), ("ALIBI", "Crime excuse"), ("ALIGN", "Straighten"),
    ("ALIVE", "Not dead"), ("ALLEY", "Narrow lane"), ("ALLOY", "Metal mix"),
    ("ANGEL", "Heavenly being"), ("ANGER", "Fury"), ("ANGLE", "Corner degree"),
    ("ANKLE", "Foot joint"), ("APPLE", "Red fruit"), ("ARENA", "Sports venue"),
    ("ARISE", "Get up"), ("ARMOR", "Knight's suit"), ("AROMA", "Pleasant smell"),
    ("ASIDE", "To one side"), ("ATLAS", "Map book"), ("ATTIC", "House top"),
    ("AVOID", "Stay away from"), ("BADGE", "ID pin"), ("BASIC", "Fundamental"),
    ("BASIN", "Wash bowl"), ("BEACH", "Sandy shore"), ("BEGUN", "Started"),
    ("BENCH", "Park seat"), ("BLACK", "Darkest color"), ("BLADE", "Knife edge"),
    ("BLAME", "Hold responsible"), ("BLANK", "Empty"), ("BLAST", "Explosion"),
    ("BLAZE", "Fire"), ("BLEED", "Lose blood"), ("BLEND", "Mix together"),
    ("BLESS", "Give thanks"), ("BLIND", "Can't see"), ("BLISS", "Pure joy"),
    ("BLOCK", "Obstruct"), ("BLOOM", "Flower"), ("BLOWN", "Past of blow"),
    ("BLUNT", "Not sharp"), ("BOARD", "Plank"), ("BOOST", "Increase"),
    ("BOUND", "Tied"), ("BRAIN", "Thinking organ"), ("BRAND", "Product name"),
    ("BRAVE", "Courageous"), ("BREAD", "Loaf"), ("BREAK", "Snap"),
    ("BREED", "Animal type"), ("BRICK", "Building block"), ("BRIEF", "Short"),
    ("BRING", "Carry to"), ("BRISK", "Lively pace"), ("BROAD", "Wide"),
    ("BROOK", "Small stream"), ("BRUSH", "Hair tool"), ("BUILD", "Construct"),
    ("BURST", "Pop"), ("CABIN", "Log home"), ("CABLE", "Thick wire"),
    ("CAMEL", "Desert animal"), ("CANDY", "Sweet treat"), ("CARGO", "Ship's load"),
    ("CARRY", "Transport"), ("CATCH", "Grab"), ("CAUSE", "Reason"),
    ("CEDAR", "Fragrant tree"), ("CHAIN", "Link series"), ("CHAIR", "Seat"),
    ("CHALK", "Writing stick"), ("CHARM", "Allure"), ("CHASE", "Pursue"),
    ("CHEAP", "Inexpensive"), ("CHECK", "Verify"), ("CHEER", "Shout of joy"),
    ("CHESS", "Board game"), ("CHEST", "Treasure box"), ("CHIEF", "Leader"),
    ("CHILD", "Young person"), ("CHILL", "Cool down"), ("CHINA", "Porcelain"),
    ("CHOIR", "Singing group"), ("CIVIL", "Polite"), ("CLAIM", "Assert"),
    ("CLASH", "Conflict"), ("CLASS", "School group"), ("CLEAN", "Not dirty"),
    ("CLEAR", "Transparent"), ("CLERK", "Office worker"), ("CLIFF", "Steep rock"),
    ("CLIMB", "Go up"), ("CLING", "Hold tight"), ("CLOCK", "Time teller"),
    ("CLOSE", "Shut"), ("CLOTH", "Fabric"), ("CLOUD", "Sky puff"),
    ("CLOWN", "Circus performer"), ("COACH", "Trainer"), ("COAST", "Shoreline"),
    ("CORAL", "Reef builder"), ("COULD", "Was able"), ("COUNT", "Number"),
    ("COUCH", "Living room seat"), ("COURT", "Tennis area"), ("COVER", "Hide"),
    ("CRACK", "Split"), ("CRAFT", "Skilled trade"), ("CRANE", "Tall bird"),
    ("CRASH", "Collision"), ("CRAWL", "Move slowly"), ("CRAZY", "Insane"),
    ("CREAM", "Coffee addition"), ("CREEK", "Small stream"), ("CREST", "Wave top"),
    ("CRIME", "Illegal act"), ("CRISP", "Crunchy"), ("CROSS", "Angry"),
    ("CROWD", "Large group"), ("CROWN", "Royal headpiece"), ("CRUEL", "Mean"),
    ("CRUSH", "Squeeze"), ("CURVE", "Bend"), ("CYCLE", "Repeat pattern"),
    ("DAILY", "Every day"), ("DANCE", "Move to music"), ("DEALT", "Gave cards"),
    ("DELAY", "Postpone"), ("DENSE", "Thick"), ("DEPTH", "Deepness"),
    ("DIARY", "Journal"), ("DITCH", "Roadside channel"), ("DIZZY", "Lightheaded"),
    ("DOUBT", "Uncertainty"), ("DOUGH", "Bread mix"), ("DRAFT", "Rough copy"),
    ("DRAIN", "Empty"), ("DRAMA", "Stage play"), ("DRANK", "Consumed liquid"),
    ("DRAPE", "Curtain"), ("DRAWN", "Sketched"), ("DREAD", "Fear greatly"),
    ("DREAM", "Sleep vision"), ("DRESS", "Garment"), ("DRIED", "Not wet"),
    ("DRIFT", "Float along"), ("DRILL", "Boring tool"), ("DRINK", "Beverage"),
    ("DRIVE", "Steer a car"), ("DROVE", "Past of drive"), ("DROWN", "Sink"),
    ("DUSTY", "Needs cleaning"), ("DYING", "Fading"), ("EAGER", "Keen"),
    ("EAGLE", "Bald bird"), ("EARLY", "Before time"), ("EARTH", "Our planet"),
    ("EIGHT", "After seven"), ("ELDER", "Older one"), ("ELECT", "Vote in"),
    ("EMPTY", "Nothing inside"), ("ENEMY", "Foe"), ("ENJOY", "Like a lot"),
    ("ENTER", "Go in"), ("ENTRY", "Doorway"), ("EQUAL", "Same amount"),
    ("ERASE", "Rub out"), ("ERROR", "Mistake"), ("EVENT", "Occurrence"),
    ("EVERY", "Each one"), ("EXACT", "Precise"), ("EXTRA", "Additional"),
    ("FABLE", "Moral story"), ("FAIRY", "Tiny sprite"), ("FAITH", "Trust"),
    ("FALSE", "Not true"), ("FANCY", "Elaborate"), ("FEAST", "Big meal"),
    ("FENCE", "Yard divider"), ("FERRY", "Water taxi"), ("FEVER", "High temp"),
    ("FIBER", "Thread"), ("FIELD", "Open land"), ("FIGHT", "Battle"),
    ("FINAL", "Last"), ("FLAME", "Fire tongue"), ("FLARE", "Signal light"),
    ("FLASH", "Quick light"), ("FLASK", "Small bottle"), ("FLEET", "Ship group"),
    ("FLESH", "Body tissue"), ("FLOAT", "Stay on top"), ("FLOCK", "Sheep group"),
    ("FLOOD", "Water overflow"), ("FLOOR", "Room bottom"), ("FLOUR", "Baking powder"),
    ("FLUID", "Liquid"), ("FLUTE", "Wind instrument"), ("FOCUS", "Concentrate"),
    ("FOGGY", "Misty"), ("FORCE", "Power"), ("FORGE", "Blacksmith's shop"),
    ("FRAME", "Picture border"), ("FRANK", "Honest"), ("FRAUD", "Scam"),
    ("FRESH", "Newly made"), ("FRONT", "Ahead"), ("FROST", "Ice crystals"),
    ("FROZE", "Turned to ice"), ("FRUIT", "Apple or orange"), ("FULLY", "Completely"),
    ("FUNNY", "Humorous"), ("GIANT", "Huge person"), ("GIVEN", "Donated"),
    ("GLARE", "Harsh stare"), ("GLASS", "Drinking vessel"), ("GLEAM", "Shine"),
    ("GLOBE", "World model"), ("GLOOM", "Darkness"), ("GLOSS", "Shiny finish"),
    ("GLOVE", "Hand cover"), ("GOING", "Leaving"), ("GRACE", "Elegance"),
    ("GRADE", "School mark"), ("GRAIN", "Wheat particle"), ("GRAND", "Magnificent"),
    ("GRANT", "Award"), ("GRAPE", "Wine fruit"), ("GRASP", "Understand"),
    ("GRASS", "Lawn cover"), ("GRATE", "Shred"), ("GRAVE", "Burial site"),
    ("GRAVEL", "Small stones"), ("GRAZE", "Eat grass"), ("GREAT", "Wonderful"),
    ("GREED", "Want too much"), ("GREEN", "Grass color"), ("GREET", "Say hello"),
    ("GRIEF", "Deep sorrow"), ("GRILL", "BBQ cook"), ("GRIND", "Crush fine"),
    ("GROAN", "Pain sound"), ("GROOM", "Bride's partner"), ("GROPE", "Feel blindly"),
    ("GROUP", "Collection"), ("GROVE", "Small forest"), ("GROWL", "Dog's warning"),
    ("GROWN", "Matured"), ("GUARD", "Protector"), ("GUESS", "Estimate"),
    ("GUIDE", "Show the way"), ("GUILT", "Remorse"), ("HABIT", "Routine"),
    ("HARSH", "Severe"), ("HASTE", "Hurry"), ("HAVEN", "Safe place"),
    ("HEART", "Love organ"), ("HEDGE", "Garden border"), ("HERON", "Wading bird"),
    ("HOIST", "Lift up"), ("HONEY", "Bee product"), ("HONOR", "Respect"),
    ("HORSE", "Riding animal"), ("HOTEL", "Lodging place"), ("HOUSE", "Dwelling"),
    ("HUMAN", "Person"), ("HUMOR", "Comedy"), ("HURRY", "Rush"),
    ("IDEAL", "Perfect"), ("IMAGE", "Picture"), ("INDEX", "Book listing"),
    ("INNER", "Inside"), ("INPUT", "Data entered"), ("ISSUE", "Problem"),
    ("IVORY", "Piano key material"), ("JEWEL", "Gemstone"), ("JOINT", "Connection"),
    ("JUDGE", "Court official"), ("JUICE", "Fruit drink"), ("KEEPS", "Retains"),
    ("KNIFE", "Cutting tool"), ("KNOCK", "Rap on door"), ("LABEL", "Name tag"),
    ("LATCH", "Door catch"), ("LATER", "Afterward"), ("LAUGH", "Chuckle"),
    ("LAYER", "Coating"), ("LEASE", "Rental agreement"), ("LEAVE", "Depart"),
    ("LEGAL", "Lawful"), ("LEMON", "Sour citrus"), ("LEVEL", "Flat"),
    ("LIGHT", "Illumination"), ("LILAC", "Purple flower"), ("LINEN", "Bed fabric"),
    ("LIVER", "Body organ"), ("LOCAL", "Nearby"), ("LODGE", "Mountain cabin"),
    ("LOGIC", "Reasoning"), ("LOOSE", "Not tight"), ("LOVER", "Romantic one"),
    ("LOWER", "Reduce"), ("LOYAL", "Faithful"), ("LUNAR", "Moon-related"),
    ("LUNCH", "Midday meal"), ("MAGIC", "Illusion art"), ("MAJOR", "Important"),
    ("MAPLE", "Syrup tree"), ("MARCH", "Third month"), ("MATCH", "Game"),
    ("MAYOR", "City leader"), ("MEDIA", "News outlets"), ("MELON", "Summer fruit"),
    ("MERCY", "Compassion"), ("METAL", "Iron or steel"), ("METER", "Measuring device"),
    ("MIGHT", "Power"), ("MINOR", "Small"), ("MIRTH", "Laughter"),
    ("MODEL", "Fashion poser"), ("MONEY", "Cash"), ("MONTH", "Year division"),
    ("MORAL", "Lesson"), ("MOUNT", "Climb"), ("MOUSE", "Computer clicker"),
    ("MOUTH", "Speaking organ"), ("MOVIE", "Film"), ("MUDDY", "Dirty"),
    ("MUSIC", "Melody"), ("NERVE", "Body fiber"), ("NIGHT", "After sunset"),
    ("NOBLE", "Distinguished"), ("NOISE", "Loud sound"), ("NORTH", "Compass point"),
    ("NOTED", "Famous"), ("NOVEL", "Book"), ("NURSE", "Hospital worker"),
    ("OCEAN", "Vast water"), ("OFFER", "Propose"), ("OFTEN", "Frequently"),
    ("OLIVE", "Green fruit"), ("ONSET", "Beginning"), ("OPERA", "Musical drama"),
    ("ORBIT", "Space path"), ("ORDER", "Arrangement"), ("ORGAN", "Body part"),
    ("OTHER", "Different"), ("OUTER", "External"), ("OWNER", "Possessor"),
    ("OXIDE", "Rust compound"), ("PAINT", "Wall color"), ("PANEL", "Flat board"),
    ("PANIC", "Sudden fear"), ("PAPER", "Writing surface"), ("PARTY", "Celebration"),
    ("PASTA", "Italian food"), ("PATCH", "Repair piece"), ("PAUSE", "Stop briefly"),
    ("PEACE", "No war"), ("PEACH", "Fuzzy fruit"), ("PEARL", "Oyster gem"),
    ("PEDAL", "Bike part"), ("PHASE", "Stage"), ("PHOTO", "Picture"),
    ("PIANO", "Keyboard instrument"), ("PIECE", "Part"), ("PILOT", "Plane driver"),
    ("PITCH", "Throw"), ("PIXEL", "Screen dot"), ("PIZZA", "Italian pie"),
    ("PLACE", "Location"), ("PLAIN", "Simple"), ("PLANE", "Aircraft"),
    ("PLANT", "Green organism"), ("PLATE", "Dinner dish"), ("PLAZA", "Public square"),
    ("PLEAD", "Beg"), ("PLUMB", "Vertical"), ("POINT", "Tip"),
    ("POLAR", "Arctic"), ("PORCH", "Front entrance"), ("POUCH", "Small bag"),
    ("POUND", "British currency"), ("POWER", "Strength"), ("PRESS", "Push"),
    ("PRICE", "Cost"), ("PRIDE", "Self-esteem"), ("PRIME", "First quality"),
    ("PRINT", "Make copies"), ("PRIOR", "Before"), ("PRIZE", "Award"),
    ("PROOF", "Evidence"), ("PROUD", "Pleased"), ("PROVE", "Demonstrate"),
    ("PRUNE", "Dried plum"), ("PULSE", "Heartbeat"), ("PUNCH", "Hit hard"),
    ("PUPIL", "Student"), ("PURSE", "Handbag"), ("QUEEN", "Royal woman"),
    ("QUEST", "Search"), ("QUICK", "Fast"), ("QUIET", "Silent"),
    ("QUOTE", "Repeat words"), ("RADAR", "Detection system"), ("RAISE", "Lift up"),
    ("RALLY", "Mass meeting"), ("RANCH", "Cattle farm"), ("RANGE", "Mountain chain"),
    ("RAPID", "Very fast"), ("RAZOR", "Shaving blade"), ("REACH", "Extend to"),
    ("REALM", "Kingdom"), ("REIGN", "Rule"), ("RELAY", "Pass along"),
    ("RIDGE", "Mountain crest"), ("RIFLE", "Long gun"), ("RIGHT", "Correct"),
    ("RIGID", "Stiff"), ("RINSE", "Wash lightly"), ("RISKY", "Dangerous"),
    ("RIVAL", "Competitor"), ("RIVER", "Flowing water"), ("ROBIN", "Red-breasted bird"),
    ("ROBOT", "Mechanical being"), ("ROCKY", "Full of stones"), ("ROUGE", "Blush makeup"),
    ("ROUGH", "Not smooth"), ("ROUND", "Circular"), ("ROUTE", "Path"),
    ("ROYAL", "Kingly"), ("RULER", "Measuring stick"), ("RURAL", "Country"),
    ("SADLY", "Unhappily"), ("SAINT", "Holy person"), ("SALAD", "Green dish"),
    ("SAUCE", "Food topping"), ("SCALE", "Weigh"), ("SCARE", "Frighten"),
    ("SCARF", "Neck warmer"), ("SCENE", "Movie part"), ("SCENT", "Fragrance"),
    ("SCORE", "Game points"), ("SCOUT", "Explorer"), ("SCRUB", "Clean hard"),
    ("SENSE", "Feeling"), ("SERVE", "Wait on"), ("SEVEN", "Lucky number"),
    ("SHADE", "Shadow"), ("SHALL", "Will"), ("SHAME", "Disgrace"),
    ("SHAPE", "Form"), ("SHARE", "Divide"), ("SHARK", "Ocean predator"),
    ("SHARP", "Keen edge"), ("SHAWL", "Shoulder wrap"), ("SHEAR", "Cut wool"),
    ("SHEER", "Absolute"), ("SHEET", "Bed linen"), ("SHELF", "Wall ledge"),
    ("SHELL", "Hard outer cover"), ("SHIFT", "Change"), ("SHINE", "Glow"),
    ("SHIRT", "Upper garment"), ("SHOCK", "Surprise"), ("SHORE", "Waterfront"),
    ("SHORT", "Not tall"), ("SHOUT", "Yell"), ("SHOVE", "Push hard"),
    ("SIEGE", "Fortress attack"), ("SIGHT", "Vision"), ("SINCE", "From then"),
    ("SIXTH", "After fifth"), ("SIXTY", "Six tens"), ("SKATE", "Ice glider"),
    ("SKILL", "Ability"), ("SKULL", "Head bone"), ("SLASH", "Cut"),
    ("SLATE", "Roof stone"), ("SLAVE", "Forced worker"), ("SLEEP", "Nightly rest"),
    ("SLICE", "Thin piece"), ("SLIDE", "Playground ride"), ("SLOPE", "Incline"),
    ("SMART", "Intelligent"), ("SMELL", "Odor"), ("SMILE", "Happy face"),
    ("SMOKE", "Fire output"), ("SNACK", "Small bite"), ("SNAIL", "Slow creature"),
    ("SNAKE", "Legless reptile"), ("SOLAR", "Sun-powered"), ("SOLID", "Not liquid"),
    ("SOLVE", "Figure out"), ("SOUTH", "Compass point"), ("SPACE", "Outer region"),
    ("SPARE", "Extra"), ("SPARK", "Fire start"), ("SPEAK", "Talk"),
    ("SPEED", "Velocity"), ("SPELL", "Magic words"), ("SPEND", "Use money"),
    ("SPICE", "Food seasoning"), ("SPINE", "Backbone"), ("SPOKE", "Said"),
    ("SPOON", "Eating utensil"), ("SPORT", "Athletic game"), ("SPRAY", "Mist"),
    ("STACK", "Pile up"), ("STAFF", "Workers"), ("STAGE", "Theater platform"),
    ("STAIN", "Spot"), ("STAIR", "Step"), ("STAKE", "Wager"),
    ("STALE", "Not fresh"), ("STALL", "Delay"), ("STAMP", "Postage"),
    ("STAND", "Get up"), ("STARE", "Gaze"), ("START", "Begin"),
    ("STATE", "Condition"), ("STAVE", "Ward off"), ("STEAK", "Beef cut"),
    ("STEAL", "Pilfer"), ("STEAM", "Hot vapor"), ("STEEL", "Strong metal"),
    ("STEEP", "Very angled"), ("STEER", "Guide"), ("STERN", "Ship's rear"),
    ("STICK", "Branch"), ("STIFF", "Rigid"), ("STILL", "Motionless"),
    ("STING", "Bee attack"), ("STINK", "Bad smell"), ("STOCK", "Supply"),
    ("STOLE", "Past of steal"), ("STONE", "Rock"), ("STOOD", "Was standing"),
    ("STOOL", "Bar seat"), ("STORE", "Shop"), ("STORM", "Bad weather"),
    ("STORY", "Tale"), ("STOVE", "Kitchen range"), ("STRAW", "Drinking tube"),
    ("STRAY", "Lost animal"), ("STRIP", "Narrow piece"), ("STUCK", "Can't move"),
    ("STUDY", "Learn"), ("STUMP", "Tree base"), ("STYLE", "Fashion"),
    ("SUGAR", "Sweet granules"), ("SUITE", "Hotel room"), ("SUNNY", "Bright day"),
    ("SUPER", "Great"), ("SWAMP", "Wetland"), ("SWARM", "Bee group"),
    ("SWEAR", "Promise"), ("SWEAT", "Perspire"), ("SWEEP", "Broom work"),
    ("SWEET", "Sugary"), ("SWEPT", "Cleaned up"), ("SWIFT", "Very fast"),
    ("SWING", "Playground fun"), ("SWORD", "Knight's weapon"), ("SWORE", "Promised"),
    ("TABLE", "Dining surface"), ("TASTE", "Flavor"), ("TEACH", "Instruct"),
    ("TEMPO", "Music speed"), ("THANK", "Express gratitude"), ("THEFT", "Robbery"),
    ("THEME", "Central idea"), ("THICK", "Not thin"), ("THIEF", "Robber"),
    ("THINK", "Ponder"), ("THIRD", "After second"), ("THORN", "Rose prickle"),
    ("THREE", "After two"), ("THREW", "Tossed"), ("THROW", "Toss"),
    ("THUMB", "Short finger"), ("TIGER", "Striped cat"), ("TIGHT", "Snug"),
    ("TIMER", "Clock device"), ("TITLE", "Book name"), ("TOAST", "Breakfast bread"),
    ("TODAY", "This day"), ("TOKEN", "Game piece"), ("TORCH", "Flashlight"),
    ("TOTAL", "Sum"), ("TOUCH", "Feel"), ("TOUGH", "Hard"),
    ("TOWER", "Tall structure"), ("TOXIC", "Poisonous"), ("TRACE", "Outline"),
    ("TRACK", "Running path"), ("TRADE", "Exchange"), ("TRAIL", "Hiking path"),
    ("TRAIN", "Rail vehicle"), ("TRAIT", "Characteristic"), ("TRASH", "Garbage"),
    ("TREAD", "Walk on"), ("TREAT", "Special gift"), ("TREND", "Fashion"),
    ("TRIAL", "Court hearing"), ("TRIBE", "Native group"), ("TRICK", "Prank"),
    ("TRIED", "Attempted"), ("TROOP", "Soldier group"), ("TRUCK", "Hauling vehicle"),
    ("TRULY", "Really"), ("TRUMP", "Card suit winner"), ("TRUNK", "Tree base"),
    ("TRUST", "Have faith"), ("TRUTH", "Honest fact"),
    ("TUTOR", "Private teacher"), ("TWICE", "Two times"), ("TWIST", "Turn"),
    ("ULTRA", "Extreme"), ("UNCLE", "Parent's brother"), ("UNDER", "Below"),
    ("UNION", "Workers group"), ("UNITE", "Join together"), ("UNITY", "Togetherness"),
    ("UNTIL", "Up to"), ("UPPER", "Higher"), ("UPSET", "Disturbed"),
    ("URBAN", "City-like"), ("USAGE", "Use"), ("USUAL", "Normal"),
    ("UTTER", "Complete"), ("VALID", "Legitimate"), ("VALUE", "Worth"),
    ("VAPOR", "Steam"), ("VAULT", "Bank safe"), ("VIDEO", "Recorded clip"),
    ("VIGOR", "Energy"), ("VIRAL", "Spreading fast"), ("VISIT", "Go see"),
    ("VITAL", "Essential"), ("VIVID", "Bright"), ("VOCAL", "Spoken"),
    ("VOICE", "Speaking sound"), ("VOTER", "Ballot caster"), ("WAGON", "Pull cart"),
    ("WAIST", "Body middle"), ("WASTE", "Garbage"), ("WATCH", "Wrist clock"),
    ("WATER", "H2O"), ("WEARY", "Tired"), ("WEAVE", "Make cloth"),
    ("WEDGE", "Door stopper"), ("WHALE", "Ocean giant"), ("WHEAT", "Bread grain"),
    ("WHEEL", "Round mover"), ("WHERE", "What place"), ("WHILE", "During"),
    ("WHITE", "Snow color"), ("WHOLE", "Complete"), ("WHOSE", "Belonging to whom"),
    ("WIDER", "More broad"), ("WIDTH", "Broadness"), ("WINDY", "Breezy"),
    ("WITCH", "Halloween figure"), ("WOMAN", "Adult female"), ("WORLD", "Earth"),
    ("WORRY", "Fret"), ("WORSE", "More bad"), ("WORST", "Most bad"),
    ("WORTH", "Value"), ("WOULD", "Conditional"), ("WOUND", "Injury"),
    ("WRIST", "Hand joint"), ("WROTE", "Penned"), ("YACHT", "Fancy boat"),
    ("YIELD", "Give way"), ("YOUNG", "Not old"), ("YOUTH", "Young person"),
    # ── 5-letter crossword fill ──
    ("AERIE", "Eagle's nest"), ("AFOOT", "Walking"), ("AGAPE", "Wide open"),
    ("AGATE", "Marble type"), ("AGAVE", "Tequila plant"),
    ("AISLE", "Theater walkway"), ("ALLAY", "Calm"), ("AMASS", "Accumulate"),
    ("AMPLE", "More than enough"), ("ANIME", "Japanese animation"),
    ("ANISE", "Licorice-flavored herb"), ("APNEA", "Sleep disorder"),
    ("ATONE", "Make amends"), ("AVERT", "Turn away"), ("AZURE", "Sky blue"),
    ("BASIL", "Italian herb"), ("BAYOU", "Louisiana waterway"),
    ("BEIGE", "Neutral color"), ("BERET", "French cap"),
    ("BIBLE", "Holy book"), ("BLASE", "Unimpressed"),
    ("CAPER", "Prank"),
    ("CREED", "Set of beliefs"), ("EASEL", "Painter's stand"),
    ("EATER", "Diner"), ("ECLAT", "Brilliance"), ("EDGER", "Lawn tool"),
    ("EERIE", "Spooky"), ("EGRET", "White wading bird"),
    ("ELATE", "Thrill"), ("ELFIN", "Small and sprightly"),
    ("EMBER", "Dying coal"), ("EMCEE", "Show host"), ("EMOTE", "Act dramatically"),
    ("ENACT", "Pass into law"), ("ENDOW", "Bestow"), ("ENNUI", "Boredom"),
    ("ENVOY", "Diplomat"), ("EPOXY", "Strong glue"), ("ERODE", "Wear away"),
    ("ETUDE", "Musical exercise"), ("EVADE", "Dodge"), ("EXUDE", "Ooze"),
    ("FIORD", "Norwegian inlet"), ("FORTE", "Strong suit"),
    ("GUISE", "Disguise"), ("HAIKU", "Japanese poem form"),
    ("IDIOM", "Figure of speech"), ("LLAMA", "Andean animal"),
    ("NADIR", "Lowest point"), ("OAKEN", "Made of sturdy wood"),
    ("OATER", "Western movie"), ("OCTET", "Group of eight"),
    ("OTTER", "Playful swimmer"), ("OUIJA", "Board game"),
    ("OVATE", "Egg-shaped"),
    ("PAEAN", "Song of praise"), ("PATIO", "Outdoor area"),
    ("PUREE", "Blended soup"), ("REBUS", "Puzzle with pictures"),
    ("REGAL", "Royal"), ("REVUE", "Stage show"),
    ("SALSA", "Chip dip"), ("SALVO", "Volley"), ("SAUNA", "Steam bath"),
    ("SEDAN", "Four-door car"), ("SEPIA", "Brownish tone"),
    ("STAID", "Sedate"), ("STOIC", "Unemotional"), ("STUPA", "Buddhist shrine"),
    ("SUAVE", "Smooth"), ("TABOO", "Forbidden"), ("TEPEE", "Native dwelling"),
    ("TIARA", "Princess crown"), ("TRUCE", "Ceasefire"), ("UKASE", "Decree"),
    ("USHER", "Theater guide"),
    ("UTILE", "Useful"), ("ABODE", "Home"), ("ADAGE", "Old saying"),
    ("ADORE", "Love deeply"),
    ("ALLOT", "Distribute"), ("ALOFT", "Up high"), ("AMAZE", "Astound"),
    ("ANGST", "Anxiety"), ("ABYSS", "Bottomless pit"),
    ("CARAT", "Diamond unit"), ("INANE", "Silly"),
    ("LLANO", "Treeless plain"), ("OASIS", "Desert refuge"),
    ("OPTIC", "Eye-related"), ("OSIER", "Willow"), ("ULCER", "Stomach woe"),
    ("ANEAR", "Close to, archaic"), ("AGLOW", "Radiant"),
    ("AWFUL", "Terrible"), ("CHOKE", "Gag"),
    ("DIVES", "Underwater swims"),

    # ── 6-letter words ─────────────────────────────────
    ("ABSORB", "Soak up"), ("ACCENT", "Speech pattern"), ("ACCEPT", "Agree to take"),
    ("ACCESS", "Entry"), ("ACROSS", "From side to side"), ("ACTION", "Activity"),
    ("ACTIVE", "Energetic"), ("ACTUAL", "Real"), ("ADVICE", "Guidance"),
    ("AFFIRM", "Confirm"), ("AGENDA", "Meeting plan"), ("ALMOST", "Nearly"),
    ("ALPINE", "Mountain"), ("ALWAYS", "Forever"), ("AMOUNT", "Quantity"),
    ("ANCHOR", "Ship stopper"), ("ANIMAL", "Creature"), ("ANNUAL", "Yearly"),
    ("ANSWER", "Reply"), ("APPEAL", "Request"), ("APPEAR", "Show up"),
    ("ARCTIC", "Polar region"), ("ARRIVE", "Come"), ("ARTIST", "Painter"),
    ("ASSIGN", "Give task"), ("ASSIST", "Help"), ("ASSUME", "Suppose"),
    ("ATTACH", "Fasten"), ("ATTACK", "Assault"), ("ATTEND", "Be present"),
    ("AUTHOR", "Book writer"), ("AWAKEN", "Rouse"), ("BANANA", "Yellow fruit"),
    ("BASKET", "Woven container"), ("BATTLE", "Fight"), ("BEAUTY", "Loveliness"),
    ("BECOME", "Turn into"), ("BEFORE", "Prior to"), ("BEHOLD", "Look at"),
    ("BELONG", "Be part of"), ("BESIDE", "Next to"), ("BEYOND", "Past"),
    ("BISHOP", "Chess piece"), ("BITTER", "Sharp taste"), ("BLANCH", "Turn pale"),
    ("BORDER", "Edge"), ("BOTHER", "Annoy"), ("BOTTOM", "Lowest part"),
    ("BOUNCE", "Spring back"), ("BRANCH", "Tree limb"), ("BREEZE", "Light wind"),
    ("BRIDGE", "River crossing"), ("BRONZE", "Copper alloy"), ("BUBBLE", "Soap sphere"),
    ("BUCKET", "Pail"), ("BUDGET", "Spending plan"), ("BUNDLE", "Package"),
    ("BURDEN", "Heavy load"), ("BUTTON", "Shirt fastener"), ("BUYING", "Purchasing"),
    ("CACTUS", "Desert plant"), ("CANDLE", "Wax light"), ("CANVAS", "Paint surface"),
    ("CARBON", "Element #6"), ("CAREER", "Life's work"), ("CARPET", "Floor covering"),
    ("CASTLE", "King's home"), ("CAUGHT", "Past of catch"), ("CENTER", "Middle"),
    ("CHANCE", "Opportunity"), ("CHANGE", "Alter"), ("CHARGE", "Electric flow"),
    ("CHEESE", "Pizza topping"), ("CHOICE", "Option"), ("CHOOSE", "Pick"),
    ("CHURCH", "Worship place"), ("CIRCLE", "Round shape"), ("CLIENT", "Customer"),
    ("CLOSET", "Clothes storage"), ("COBALT", "Blue metal"), ("COFFEE", "Morning brew"),
    ("COLONY", "Settlement"), ("COLUMN", "Pillar"), ("COMEDY", "Funny show"),
    ("COMMON", "Ordinary"), ("CONVEY", "Transport"), ("COOKIE", "Sweet snack"),
    ("COPPER", "Penny metal"), ("CORNER", "Angle"), ("COSMIC", "Universal"),
    ("COTTON", "Fabric type"), ("COUPLE", "Pair"), ("COURSE", "Class"),
    ("COUSIN", "Relative"), ("CREATE", "Make"), ("CRISIS", "Emergency"),
    ("CUSTOM", "Tradition"), ("DAMAGE", "Harm"), ("DANGER", "Risk"),
    ("DARING", "Bold"), ("DEBATE", "Argument"), ("DECENT", "Proper"),
    ("DEFEAT", "Beat"), ("DEFEND", "Protect"), ("DEFINE", "Explain meaning"),
    ("DEGREE", "Temperature unit"), ("DEMAND", "Require"), ("DENTAL", "Tooth-related"),
    ("DEPART", "Leave"), ("DEPEND", "Rely on"), ("DESERT", "Sandy wasteland"),
    ("DESIGN", "Plan"), ("DESIRE", "Want"), ("DETAIL", "Particular"),
    ("DETECT", "Discover"), ("DEVICE", "Gadget"), ("DEVOTE", "Dedicate"),
    ("DINNER", "Evening meal"), ("DIRECT", "Straight"), ("DIVIDE", "Split"),
    ("DOCTOR", "Physician"), ("DOMAIN", "Territory"), ("DONKEY", "Stubborn animal"),
    ("DOUBLE", "Twice"), ("DRAGON", "Mythical beast"), ("DRIVEN", "Motivated"),
    ("EDITOR", "Text reviser"), ("EFFECT", "Result"), ("EFFORT", "Hard work"),
    ("EMPIRE", "Vast kingdom"), ("ENABLE", "Allow"), ("ENDURE", "Bear"),
    ("ENERGY", "Power"), ("ENGAGE", "Involve"), ("ENGINE", "Motor"),
    ("ENTIRE", "Whole"), ("ESCAPE", "Get away"), ("ESTATE", "Property"),
    ("EVOLVE", "Develop"), ("EXCEED", "Go beyond"), ("EXCEPT", "Other than"),
    ("EXCITE", "Thrill"), ("EXCUSE", "Pardon"), ("EXPAND", "Grow"),
    ("EXPECT", "Anticipate"), ("EXPERT", "Specialist"), ("EXPORT", "Ship abroad"),
    ("EXTEND", "Stretch"), ("FABRIC", "Cloth"), ("FACTOR", "Element"),
    ("FAIRLY", "Justly"), ("FAMILY", "Relatives"), ("FARMER", "Crop grower"),
    ("FELLOW", "Guy"), ("FIERCE", "Ferocious"), ("FIGURE", "Number"),
    ("FILTER", "Strain"), ("FINGER", "Hand digit"), ("FINISH", "Complete"),
    ("FLIGHT", "Air travel"), ("FLOWER", "Bloom"), ("FLUENT", "Speaks well"),
    ("FLYING", "Airborne"), ("FOLLOW", "Come after"), ("FORBID", "Prohibit"),
    ("FORCED", "Made to"), ("FOREST", "Woods"), ("FORGET", "Not remember"),
    ("FORMAL", "Dressy"), ("FORMER", "Previous"), ("FOSSIL", "Ancient remains"),
    ("FREEZE", "Turn to ice"), ("FRENZY", "Wild excitement"), ("FRIEND", "Pal"),
    ("FROZEN", "Iced"), ("FUTURE", "Time ahead"), ("GALAXY", "Star system"),
    ("GARAGE", "Car shelter"), ("GARDEN", "Plant area"), ("GATHER", "Collect"),
    ("GENDER", "Male or female"), ("GENTLE", "Soft"), ("GIVING", "Generous"),
    ("GLOBAL", "Worldwide"), ("GOLDEN", "Gold-colored"), ("GOSPEL", "Good news"),
    ("GOSSIP", "Rumor"), ("GOVERN", "Rule"), ("GROWTH", "Increase"),
    ("GUITAR", "Six-string"), ("GUTTER", "Rain channel"), ("HANDLE", "Grip"),
    ("HAPPEN", "Occur"), ("HARBOR", "Port"), ("HAVING", "Possessing"),
    ("HEALTH", "Wellness"), ("HEAVEN", "Paradise"), ("HIDING", "Concealing"),
    ("HIKING", "Trail walking"), ("HOLLOW", "Empty inside"), ("HONEST", "Truthful"),
    ("HOPING", "Wishing"), ("HORROR", "Fright"), ("HUNGER", "Need for food"),
    ("HUNTER", "Game tracker"), ("HYBRID", "Mixed breed"), ("ICEBERG", "Floating ice"),
    ("IGNITE", "Start fire"), ("IGNORE", "Disregard"), ("IMPACT", "Effect"),
    ("IMPORT", "Bring in"), ("IMPOSE", "Force upon"), ("INCOME", "Earnings"),
    ("INDEED", "Truly"), ("INDOOR", "Inside"), ("INFANT", "Baby"),
    ("INFORM", "Tell"), ("INJURY", "Hurt"), ("INSECT", "Bug"),
    ("INSERT", "Put in"), ("INSIDE", "Interior"), ("INSIST", "Demand"),
    ("INTACT", "Undamaged"), ("INTEND", "Plan to"), ("INVENT", "Create new"),
    ("INVEST", "Put money in"), ("INVITE", "Ask to come"), ("ISLAND", "Land in water"),
    ("ITSELF", "Reflexive it"), ("JACKET", "Light coat"), ("JIGSAW", "Puzzle type"),
    ("JUNGLE", "Dense forest"), ("JUNIOR", "Younger"), ("KEEPER", "Guard"),
    ("KERNEL", "Seed core"), ("KIDNEY", "Body organ"), ("KILLER", "Slayer"),
    ("KITTEN", "Baby cat"), ("KNIGHT", "Armored warrior"), ("LADDER", "Climbing device"),
    ("LAUNCH", "Start"), ("LAWYER", "Attorney"), ("LEADER", "Chief"),
    ("LEGEND", "Famous story"), ("LENDER", "Loan giver"), ("LESSON", "Teaching"),
    ("LETTER", "Alphabet unit"), ("LIGHTS", "Lamps"), ("LIKELY", "Probable"),
    ("LINGER", "Stay on"), ("LISTEN", "Hear"), ("LITTLE", "Small"),
    ("LIVELY", "Energetic"), ("LIVING", "Alive"), ("LIZARD", "Small reptile"),
    ("LOCATE", "Find"), ("LONELY", "Isolated"), ("LOOKED", "Saw"),
    ("LOOSEN", "Untighten"), ("LUMBER", "Building wood"), ("LUXURY", "Extravagance"),
    ("MAGNET", "Iron attractor"), ("MAIDEN", "Young woman"), ("MANGLE", "Damage"),
    ("MANNER", "Way"), ("MANUAL", "Handbook"), ("MARBLE", "Playing sphere"),
    ("MARGIN", "Edge"), ("MARINE", "Ocean-related"), ("MARKET", "Trading place"),
    ("MASTER", "Expert"), ("MATTER", "Substance"), ("MEADOW", "Grassy field"),
    ("MEDIUM", "Middle size"), ("MELODY", "Tune"), ("MEMBER", "Participant"),
    ("MEMORY", "Recall"), ("MENTAL", "Mind-related"), ("MENTOR", "Wise guide"),
    ("METHOD", "Way of doing"), ("MIDDLE", "Center"), ("MIGHTY", "Powerful"),
    ("MILLER", "Grain grinder"), ("MINUTE", "60 seconds"), ("MIRROR", "Reflection glass"),
    ("MOBILE", "Movable"), ("MODERN", "Current"), ("MODEST", "Humble"),
    ("MOMENT", "Instant"), ("MONKEY", "Primate"), ("MORTAL", "Not immortal"),
    ("MOTHER", "Female parent"), ("MOTION", "Movement"), ("MOTIVE", "Reason"),
    ("MUFFIN", "Baked good"), ("MURDER", "Killing"), ("MUSCLE", "Body fiber"),
    ("MUSEUM", "Art house"), ("MUTUAL", "Shared"), ("MYSELF", "Me"),
    ("NARROW", "Not wide"), ("NATION", "Country"), ("NATURE", "Natural world"),
    ("NEEDLE", "Sewing tool"), ("NEPHEW", "Sibling's son"), ("NICKEL", "Five cents"),
    ("NIMBLE", "Agile"), ("NOBODY", "No one"), ("NOODLE", "Pasta strand"),
    ("NORMAL", "Typical"), ("NOTICE", "Observe"), ("NUMBER", "Digit"),
    ("OBJECT", "Thing"), ("OBTAIN", "Get"), ("OCCUPY", "Fill"),
    ("OFFEND", "Insult"), ("OFFICE", "Work room"), ("ONLINE", "On the web"),
    ("OPPOSE", "Be against"), ("OPTION", "Choice"), ("ORANGE", "Citrus fruit"),
    ("ORCHID", "Exotic flower"), ("ORIGIN", "Source"), ("OUTFIT", "Clothing set"),
    ("OUTPUT", "Production"), ("OYSTER", "Shell creature"), ("PADDLE", "Canoe oar"),
    ("PALACE", "Royal home"), ("PANTRY", "Food closet"), ("PARADE", "March"),
    ("PARCEL", "Package"), ("PARENT", "Mom or Dad"), ("PARLOR", "Sitting room"),
    ("PARROT", "Talking bird"), ("PATROL", "Guard duty"), ("PAVING", "Road surface"),
    ("PENCIL", "Writing tool"), ("PEOPLE", "Persons"), ("PEPPER", "Spice"),
    ("PERSON", "Individual"), ("PHRASE", "Word group"), ("PILLOW", "Head rest"),
    ("PIRATE", "Sea robber"), ("PLANET", "World"), ("PLAYER", "Team member"),
    ("PLEDGE", "Promise"), ("PLENTY", "Enough"), ("PLIERS", "Gripping tool"),
    ("PLUNGE", "Dive"), ("POCKET", "Pants pouch"), ("POISON", "Toxic substance"),
    ("POLICE", "Law enforcement"), ("POLISH", "Shine"), ("POLITE", "Well-mannered"),
    ("PONDER", "Think deeply"), ("POSTER", "Wall display"), ("POTATO", "Spud"),
    ("POTTER", "Clay worker"), ("POULTRY", "Farm bird"), ("PRAISE", "Compliment"),
    ("PRAYER", "Request to God"), ("PREFER", "Like better"), ("PROFIT", "Gain"),
    ("PROMPT", "On time"), ("PROPER", "Correct"), ("PROVEN", "Confirmed"),
    ("PUBLIC", "Open to all"), ("PUNISH", "Discipline"), ("PUPPET", "String toy"),
    ("PURPLE", "Royal color"), ("PURSUE", "Chase"), ("PUZZLE", "Brain teaser"),
    ("RABBIT", "Long-eared animal"), ("RACKET", "Tennis gear"), ("RANDOM", "By chance"),
    ("RANGER", "Park guard"), ("REASON", "Cause"), ("RECALL", "Remember"),
    ("RECENT", "Not long ago"), ("RECORD", "Document"), ("REDUCE", "Lessen"),
    ("REFORM", "Improve"), ("REFUGE", "Shelter"), ("REFUSE", "Decline"),
    ("REGARD", "Consider"), ("REGIME", "Government"), ("REGION", "Area"),
    ("REJECT", "Turn down"), ("RELATE", "Connect"), ("RELIEF", "Comfort"),
    ("REMAIN", "Stay"), ("REMEDY", "Cure"), ("REMIND", "Jog memory"),
    ("REMOTE", "Far away"), ("REMOVE", "Take away"), ("RENDER", "Provide"),
    ("RENTAL", "Lease"), ("REPAIR", "Fix"), ("REPEAT", "Do again"),
    ("REPORT", "Account"), ("RESCUE", "Save"), ("RESIGN", "Quit"),
    ("RESIST", "Fight back"), ("RESORT", "Vacation spot"), ("RESULT", "Outcome"),
    ("RETAIL", "Store selling"), ("RETAIN", "Keep"), ("RETIRE", "Stop working"),
    ("RETURN", "Come back"), ("REVEAL", "Show"), ("REVIEW", "Evaluate"),
    ("REVOLT", "Rebellion"), ("REWARD", "Prize"), ("RHYTHM", "Beat"),
    ("RIBBON", "Gift decoration"), ("RIDDLE", "Puzzle"), ("RITUAL", "Ceremony"),
    ("ROCKET", "Space vehicle"), ("ROTTEN", "Decayed"), ("RUBBER", "Elastic material"),
    ("RULING", "Decision"), ("RUMBLE", "Low thunder"), ("RUNWAY", "Plane path"),
    ("RUSTIC", "Country-style"), ("SADDLE", "Horse seat"), ("SAFELY", "Without danger"),
    ("SALARY", "Worker's pay"), ("SALMON", "Pink fish"), ("SAMPLE", "Example"),
    ("SAVAGE", "Wild"), ("SCHOOL", "Learning place"), ("SCREAM", "Loud cry"),
    ("SEARCH", "Look for"), ("SEASON", "Spring or fall"), ("SECRET", "Hidden"),
    ("SECURE", "Safe"), ("SELECT", "Choose"), ("SENIOR", "Older"),
    ("SERIES", "Sequence"), ("SERMON", "Church talk"), ("SETTLE", "Resolve"),
    ("SEVERE", "Harsh"), ("SHADOW", "Dark outline"), ("SHIELD", "Protection"),
    ("SIGNAL", "Sign"), ("SILVER", "Precious metal"), ("SIMPLE", "Easy"),
    ("SINGLE", "Just one"), ("SISTER", "Female sibling"), ("SKETCH", "Quick drawing"),
    ("SLEEVE", "Arm cover"), ("SLOGAN", "Motto"), ("SLOWLY", "Not quickly"),
    ("SMOOTH", "Not rough"), ("SOCCER", "Football"), ("SOCIAL", "Friendly"),
    ("SOFTEN", "Make soft"), ("SORROW", "Sadness"), ("SOURCE", "Origin"),
    ("SPEECH", "Public talk"), ("SPIRIT", "Soul"), ("SPLASH", "Water sound"),
    ("SPONGE", "Absorbent pad"), ("SPRINT", "Fast run"), ("SQUARE", "Four-sided"),
    ("STABLE", "Horse house"), ("STATUE", "Stone figure"), ("STEADY", "Firm"),
    ("STITCH", "Sewing loop"), ("STOLEN", "Past of steal"), ("STRAIN", "Stress"),
    ("STRAND", "Beach"), ("STREAM", "Small river"), ("STREET", "Road"),
    ("STRESS", "Tension"), ("STRICT", "Stern"), ("STRIKE", "Hit"),
    ("STRING", "Thin cord"), ("STRONG", "Powerful"), ("STUDIO", "Art room"),
    ("SUBMIT", "Hand in"), ("SUDDEN", "Unexpected"), ("SUFFER", "Endure pain"),
    ("SUMMIT", "Peak"), ("SUPPLY", "Provide"), ("SURELY", "Certainly"),
    ("SURVEY", "Study"), ("SWITCH", "Toggle"), ("SYMBOL", "Sign"),
    ("SYSTEM", "Method"), ("TABLET", "Flat computer"), ("TACKLE", "Football move"),
    ("TALENT", "Natural ability"), ("TARGET", "Goal"), ("TEMPLE", "Worship place"),
    ("TENDER", "Soft"), ("TENNIS", "Racket sport"), ("TERROR", "Great fear"),
    ("THREAD", "Sewing string"), ("THRILL", "Excite"), ("THRONE", "King's seat"),
    ("TIMBER", "Building wood"), ("TISSUE", "Soft paper"), ("TOWARD", "In direction of"),
    ("TRAVEL", "Journey"), ("TRIBAL", "Of a tribe"), ("TROPHY", "Winner's cup"),
    ("TUNNEL", "Underground passage"), ("TURTLE", "Shell reptile"), ("UNFAIR", "Unjust"),
    ("UNIQUE", "One of a kind"), ("UNLESS", "Except if"), ("UNLIKE", "Different from"),
    ("UNREST", "Turmoil"), ("UPDATE", "Make current"), ("USEFUL", "Helpful"),
    ("VACANT", "Empty"), ("VALLEY", "Between hills"), ("VELVET", "Soft fabric"),
    ("VENDOR", "Seller"), ("VESSEL", "Ship"), ("VICTIM", "Sufferer"),
    ("Viking", "Norse warrior"), ("VISUAL", "Seen"), ("VOLUME", "Amount"),
    ("VOYAGE", "Sea journey"), ("WAITER", "Restaurant server"), ("WANDER", "Roam"),
    ("WARMTH", "Heat"), ("WEALTH", "Riches"), ("WEAPON", "Arm"),
    ("WEEKLY", "Every week"), ("WHOLLY", "Entirely"), ("WICKED", "Evil"),
    ("WINDOW", "Glass opening"), ("WINNER", "Victor"), ("WINTER", "Cold season"),
    ("WISDOM", "Knowledge"), ("WITHIN", "Inside"), ("WONDER", "Marvel"),
    ("WOODEN", "Made of wood"), ("WORKER", "Employee"), ("WORTHY", "Deserving"),
    ("WRITER", "Author"), ("YELLOW", "Sunny color"), ("ZENITH", "Highest point"),
    # ── 6-letter crossword fill ──
    ("ABLAZE", "On fire"), ("ADHERE", "Stick to"), ("ASHORE", "On land"),
    ("AVIARY", "Bird enclosure"), ("BAILEE", "Property holder"),
    ("BELUGA", "White whale"), ("BISTRO", "Small restaurant"),
    ("CALLOW", "Immature"), ("CANAPE", "Party appetizer"),
    ("COGNAC", "French brandy"), ("CRAVAT", "Necktie"),
    ("DOCENT", "Museum guide"), ("EMIGRE", "Exile"),
    ("ERASER", "Pencil end"), ("EULOGY", "Funeral speech"),
    ("FIESTA", "Mexican party"), ("GROTTO", "Small cave"),
    ("IGUANA", "Large lizard"), ("IMPALA", "African antelope"),
    ("KARATE", "Martial art"), ("LAGOON", "Shallow lake"),
    ("LESION", "Wound"), ("MANTRA", "Repeated phrase"),
    ("MARTYR", "Sacrifice maker"), ("NIECES", "Siblings' daughters"),
    ("ORDEAL", "Severe trial"), ("PALATE", "Sense of taste"),
    ("PIAZZA", "Italian square"), ("QUORUM", "Minimum number"),
    ("RATION", "Fixed portion"), ("RAPTOR", "Bird of prey"),
    ("SAFARI", "African trip"),
    ("TRUANT", "School skipper"), ("UTERUS", "Womb"),
    ("VORTEX", "Whirlpool"),
    ("ENTREE", "Main course"), ("ORNATE", "Highly decorated"),
    ("CABALA", "Mystical tradition"), ("CONGER", "Type of eel"),
    ("CURATE", "Church assistant"), ("LOCALE", "Setting"),
    ("POLICY", "Insurance document"), ("SPLICE", "Join together"),
    ("SURAH", "Quran chapter"), ("TRAUMA", "Severe shock"),
    ("TSETSE", "African fly"), ("HUNGRY", "Wanting food"),
    ("ERUDITE", "Learned"),

    # ── 7-letter words ─────────────────────────────────
    ("ABILITY", "Skill"), ("ABOLISH", "End"), ("ABSENCE", "Not being there"),
    ("ACADEMY", "School"), ("ACHIEVE", "Accomplish"), ("ACROBAT", "Circus performer"),
    ("ADDRESS", "Home location"), ("ADMIRAL", "Navy leader"), ("ADVANCE", "Move forward"),
    ("AILMENT", "Illness"), ("AIRPORT", "Plane terminal"), ("ALCHEMY", "Medieval science"),
    ("ALCOHOL", "Drink type"), ("AMAZING", "Wonderful"),
    ("AMBIENT", "Surrounding"), ("ANCIENT", "Very old"), ("ANTENNA", "Signal catcher"),
    ("ANXIETY", "Worry"), ("ANYBODY", "Any person"), ("APPLIED", "Put to use"),
    ("ARRIVAL", "Coming"), ("ARSENAL", "Weapon storage"), ("ARTICLE", "News piece"),
    ("ASPHALT", "Road material"), ("ATHLETE", "Sports person"), ("ATTEMPT", "Try"),
    ("AUCTION", "Bidding sale"), ("AUDIBLE", "Can be heard"), ("AVERAGE", "Typical"),
    ("BALANCE", "Equilibrium"), ("BANDAGE", "Wound wrap"), ("BARGAIN", "Good deal"),
    ("BATTERY", "Power source"), ("BEDROOM", "Sleep room"), ("BILLION", "Huge number"),
    ("BISCUIT", "Cookie"), ("BLANKET", "Bed cover"), ("BONFIRE", "Outdoor fire"),
    ("BOYCOTT", "Refuse to buy"), ("BREATHE", "Inhale"), ("BRITTLE", "Fragile"),
    ("BUFFALO", "Plains animal"), ("CABINET", "Storage unit"), ("CALIBER", "Quality level"),
    ("CAMPING", "Outdoor stay"), ("CAPITAL", "Main city"), ("CAPTAIN", "Ship leader"),
    ("CAPTURE", "Catch"), ("CATALOG", "Item list"), ("CAUTION", "Warning"),
    ("CENTRAL", "Middle"), ("CENTURY", "100 years"), ("CERTAIN", "Sure"),
    ("CHAMBER", "Room"), ("CHANNEL", "TV station"), ("CHAPTER", "Book section"),
    ("CHARITY", "Giving"), ("CHICKEN", "Farm bird"), ("CLIMATE", "Weather pattern"),
    ("CLUSTER", "Group"), ("COASTAL", "Near shore"), ("COLLECT", "Gather"),
    ("COLLEGE", "University"), ("COMBINE", "Join"), ("COMFORT", "Ease"),
    ("COMMAND", "Order"), ("COMMENT", "Remark"), ("COMPACT", "Small"),
    ("COMPANY", "Business"), ("COMPARE", "Contrast"), ("COMPETE", "Vie"),
    ("COMPLEX", "Complicated"), ("COMPOSE", "Write music"), ("CONCERN", "Worry"),
    ("CONDUCT", "Behavior"), ("CONFESS", "Admit"), ("CONFIRM", "Verify"),
    ("CONFUSE", "Puzzle"), ("CONNECT", "Link"), ("CONQUER", "Defeat"),
    ("CONSENT", "Agreement"), ("CONSIST", "Be made of"), ("CONSULT", "Ask advice"),
    ("CONTACT", "Touch"), ("CONTAIN", "Hold"), ("CONTENT", "Satisfied"),
    ("CONTEST", "Competition"), ("CONTEXT", "Setting"), ("CONTROL", "Command"),
    ("CONVERT", "Change"), ("COOKING", "Making food"), ("CORRECT", "Right"),
    ("COSTUME", "Outfit"), ("COTTAGE", "Small house"), ("COUNCIL", "Governing body"),
    ("COUNTER", "Kitchen top"), ("COUNTRY", "Nation"), ("COURAGE", "Bravery"),
    ("CURTAIN", "Window drape"), ("CUSHION", "Soft pillow"), ("CUSTOMS", "Border check"),
    ("DECLARE", "State"), ("DECLINE", "Decrease"), ("DEFAULT", "Standard"),
    ("DEFENSE", "Protection"), ("DEFICIT", "Shortage"), ("DEGREES", "Temperature units"),
    ("DELIVER", "Bring"), ("DENSITY", "Thickness"), ("DEPOSIT", "Bank action"),
    ("DESCENT", "Going down"), ("DESERVE", "Earn"), ("DESKTOP", "Work surface"),
    ("DESPAIR", "Hopelessness"), ("DESPITE", "In spite of"), ("DESTINY", "Fate"),
    ("DESTROY", "Wreck"), ("DEVELOP", "Grow"), ("DIALECT", "Regional speech"),
    ("DIAMOND", "Gemstone"), ("DIGITAL", "Electronic"), ("DIPLOMA", "Degree paper"),
    ("DISABLE", "Turn off"), ("DISCARD", "Throw away"), ("DISCUSS", "Talk about"),
    ("DISEASE", "Illness"), ("DISGUST", "Revulsion"), ("DISPLAY", "Show"),
    ("DISPOSE", "Get rid of"), ("DISPUTE", "Argue"), ("DISTANT", "Far away"),
    ("DISTURB", "Bother"), ("DIVERSE", "Varied"), ("DOLPHIN", "Smart mammal"),
    ("DONATED", "Gave"), ("DOORWAY", "Entry"), ("DORMANT", "Sleeping"),
    ("DRAGNET", "Wide search"), ("DYNAMIC", "Active"), ("EDITION", "Book version"),
    ("EDUCATE", "Teach"), ("ELEGANT", "Graceful"), ("ELEMENT", "Basic part"),
    ("EMOTION", "Feeling"), ("EMPEROR", "Ruler"), ("ENFORCE", "Apply law"),
    ("ENHANCE", "Improve"), ("EPISODE", "Show segment"), ("EVIDENT", "Clear"),
    ("EXAMINE", "Inspect"), ("EXAMPLE", "Sample"), ("EXCITED", "Thrilled"),
    ("EXCLUDE", "Leave out"), ("EXHIBIT", "Show"), ("EXPENSE", "Cost"),
    ("EXPLAIN", "Clarify"), ("EXPLOIT", "Use"), ("EXPLORE", "Discover"),
    ("EXPRESS", "State"), ("EXTINCT", "Died out"), ("EXTREME", "Intense"),
    ("FAILING", "Not passing"), ("FAILURE", "Defeat"), ("FALLING", "Dropping"),
    ("FASHION", "Style"), ("FEATURE", "Trait"), ("FICTION", "Made up"),
    ("FIFTEEN", "After fourteen"), ("FINDING", "Discovery"), ("FIREFLY", "Light bug"),
    ("FITTING", "Suitable"), ("FLANNEL", "Soft fabric"), ("FLATTEN", "Make flat"),
    ("FLAVOUR", "Taste"), ("FLORIDA", "Sunshine state"), ("FOREVER", "Always"),
    ("FORGAVE", "Pardoned"), ("FORMULA", "Recipe"), ("FORTUNE", "Wealth"),
    ("FORWARD", "Ahead"), ("FOUNDER", "Creator"), ("FRAGILE", "Breakable"),
    ("FREEDOM", "Liberty"), ("FREIGHT", "Cargo"), ("FULFILL", "Complete"),
    ("FUNDING", "Money"), ("FURNACE", "Heater"), ("GALLERY", "Art room"),
    ("GANGWAY", "Ship ramp"), ("GARNISH", "Food decoration"), ("GATEWAY", "Entrance"),
    ("GENERAL", "Military rank"), ("GESTURE", "Hand signal"), ("GIRAFFE", "Tall animal"),
    ("GLACIER", "Ice mass"), ("GLIMPSE", "Quick look"), ("GONDOLA", "Venice boat"),
    ("GOODBYE", "Farewell"), ("GORILLA", "Great ape"), ("GRADUAL", "Slow"),
    ("GRANITE", "Hard rock"), ("GRAVITY", "Pulling force"), ("GRIZZLY", "Bear type"),
    ("HABITAT", "Living place"), ("HALFWAY", "Middle"), ("HAMMOCK", "Hanging bed"),
    ("HANDMADE", "Not factory-made"),
    ("HARMONY", "Agreement"), ("HARVEST", "Crop gathering"), ("HEADING", "Title"),
    ("HEALTHY", "Well"), ("HEARING", "Sound sense"), ("HELPFUL", "Useful"),
    ("HIGHWAY", "Main road"), ("HIMSELF", "He"), ("HISTORY", "Past events"),
    ("HOLIDAY", "Vacation"), ("HORIZON", "Sky line"), ("HOSTILE", "Unfriendly"),
    ("HOUSING", "Shelter"), ("HOWEVER", "But"), ("HUNTING", "Sport tracking"),
    ("ILLEGAL", "Unlawful"), ("IMAGINE", "Picture"), ("IMPRESS", "Awe"),
    ("IMPROVE", "Better"), ("INCLUDE", "Contain"), ("INITIAL", "First"),
    ("INSPIRE", "Motivate"), ("INSTALL", "Set up"), ("INSTANT", "Immediate"),
    ("INSTEAD", "Rather"), ("INTERIM", "Meanwhile"), ("INVALID", "Not valid"),
    ("INVOLVE", "Include"), ("ISOLATE", "Separate"), ("JOURNEY", "Trip"),
    ("JUSTICE", "Fairness"), ("JUSTIFY", "Defend"), ("KITCHEN", "Cooking room"),
    ("KINGDOM", "Ruled land"), ("LANDING", "Arrival"), ("LANTERN", "Portable light"),
    ("LARGEST", "Biggest"), ("LASTING", "Enduring"), ("LEADING", "Top"),
    ("LEATHER", "Hide material"), ("LECTURE", "Talk"), ("LENDING", "Loaning"),
    ("LEOPARD", "Spotted cat"), ("LIBERAL", "Open-minded"), ("LIBERTY", "Freedom"),
    ("LIBRARY", "Book building"), ("LICENSE", "Permit"), ("LIGHTER", "Less heavy"),
    ("LIMITED", "Restricted"), ("LITERAL", "Exact"), ("LOCALLY", "Nearby"),
    ("LOGICAL", "Reasonable"), ("LOYALTY", "Devotion"), ("MACHINE", "Device"),
    ("MASSAGE", "Body rub"), ("MEANING", "Definition"), ("MEASURE", "Size up"),
    ("MEDICAL", "Health-related"), ("MEETING", "Gathering"), ("MILLION", "Large number"),
    ("MINERAL", "Rock substance"), ("MINIMUM", "Least"), ("MIRACLE", "Wonder"),
    ("MISSING", "Lost"), ("MISSION", "Task"), ("MISTAKE", "Error"),
    ("MIXTURE", "Blend"), ("MONSTER", "Scary creature"), ("MORNING", "Dawn time"),
    ("MUSICAL", "Song-filled"), ("MYSTERY", "Puzzle"), ("NATURAL", "Not artificial"),
    ("NEITHER", "Not either"), ("NETWORK", "Connected system"), ("NEUTRAL", "Unbiased"),
    ("NOTHING", "Zero"), ("NUCLEAR", "Atomic"), ("OBVIOUS", "Clear"),
    ("OFFENSE", "Crime"), ("OPINION", "View"), ("OPTIMAL", "Best"),
    ("ORGANIC", "Natural"), ("OUTLINE", "Summary"), ("OUTSIDE", "Exterior"),
    ("OVERALL", "General"), ("OVERLAP", "Cover partly"), ("OVERTURN", "Flip"),
    ("PADDING", "Cushioning"), ("PAINTER", "Artist"), ("PARKING", "Car lot"),
    ("PARTIAL", "Not complete"), ("PARTNER", "Teammate"), ("PASSAGE", "Hallway"),
    ("PATIENT", "Sick person"), ("PATTERN", "Design"), ("PAYMENT", "Money given"),
    ("PENALTY", "Punishment"), ("PENSION", "Retirement pay"), ("PERCENT", "Out of 100"),
    ("PERFECT", "Flawless"), ("PERHAPS", "Maybe"), ("PERSIST", "Keep going"),
    ("PHILTER", "Love potion"), ("PICTURE", "Image"), ("PIONEER", "First settler"),
    ("PLASTIC", "Synthetic"), ("PLEASED", "Happy"), ("PLUMBER", "Pipe fixer"),
    ("PLUNDER", "Loot"), ("POINTER", "Indicator"), ("POLARIS", "North star"),
    ("POPULAR", "Well-liked"), ("PORTION", "Serving"), ("POVERTY", "Need"),
    ("PREDICT", "Forecast"), ("PREMIER", "First"), ("PREMIUM", "Top quality"),
    ("PREPARE", "Get ready"), ("PRESENT", "Gift"), ("PREVENT", "Stop"),
    ("PRIMARY", "Main"), ("PRINTER", "Copy maker"), ("PRIVACY", "Solitude"),
    ("PRIVATE", "Personal"), ("PROBLEM", "Issue"), ("PROCESS", "Procedure"),
    ("PRODUCE", "Make"), ("PRODUCT", "Item"), ("PROFILE", "Outline"),
    ("PROGRAM", "Show"), ("PROJECT", "Plan"), ("PROMISE", "Vow"),
    ("PROMOTE", "Advance"), ("PROTECT", "Guard"), ("PROTEIN", "Muscle builder"),
    ("PROTEST", "Object"), ("PROVIDE", "Supply"), ("PUBLISH", "Print"),
    ("PURPOSE", "Aim"), ("PYRAMID", "Egypt shape"), ("QUALIFY", "Meet standards"),
    ("QUARTER", "Fourth"), ("QUICKLY", "Fast"), ("QUILTED", "Padded"),
    ("RADICAL", "Extreme"), ("RAILWAY", "Train tracks"), ("RAINBOW", "Color arc"),
    ("READING", "Book time"), ("REALITY", "Truth"), ("RECEIPT", "Proof of purchase"),
    ("RECEIVE", "Get"), ("RECOVER", "Heal"), ("RECYCLE", "Reuse"),
    ("REFLECT", "Mirror"), ("REGULAR", "Normal"), ("RELAXED", "Calm"),
    ("RELEASE", "Let go"), ("REMAINS", "Leftovers"), ("REMOVAL", "Taking away"),
    ("RENEWAL", "Fresh start"), ("REPLACE", "Swap"), ("REQUEST", "Ask"),
    ("REQUIRE", "Need"), ("RESERVE", "Set aside"), ("RESOLVE", "Settle"),
    ("RESPECT", "Esteem"), ("RESTORE", "Bring back"), ("RETREAT", "Pull back"),
    ("REUNION", "Getting together"), ("REVENUE", "Income"), ("REVERSE", "Opposite"),
    ("ROUTINE", "Daily habit"), ("SAILING", "Boat sport"), ("SATISFY", "Please"),
    ("SCHOLAR", "Academic"), ("SCIENCE", "Knowledge"), ("SEAFOOD", "Ocean food"),
    ("SHELTER", "Refuge"), ("SHERIFF", "Law officer"), ("SILENCE", "Quiet"),
    ("SINCERE", "Genuine"), ("SIXTEEN", "After fifteen"), ("SKILLED", "Expert"),
    ("SOCIETY", "Community"), ("SOLDIER", "Fighter"), ("SOMEHOW", "In some way"),
    ("SPEAKER", "Talker"), ("SPECIAL", "Unique"), ("SPONSOR", "Backer"),
    ("STADIUM", "Sports arena"), ("STATION", "Stop"), ("STORAGE", "Keeping place"),
    ("STRANGE", "Odd"), ("STRETCH", "Extend"), ("STUDENT", "Learner"),
    ("SUBJECT", "Topic"), ("SUCCESS", "Achievement"), ("SUGGEST", "Propose"),
    ("SUMMARY", "Brief"), ("SUPPORT", "Back up"), ("SUPREME", "Highest"),
    ("SURFACE", "Outside"), ("SURGEON", "Doctor"), ("SURPLUS", "Extra"),
    ("SURVIVE", "Live through"), ("SUSPECT", "Distrust"), ("TEACHER", "Educator"),
    ("TENSION", "Stress"), ("THERAPY", "Treatment"), ("THOUGHT", "Idea"),
    ("THUNDER", "Storm sound"), ("TOBACCO", "Smoke plant"), ("TONIGHT", "This evening"),
    ("TORNADO", "Twister"), ("TOURISM", "Travel business"), ("TRAINER", "Coach"),
    ("TRANSIT", "Transport"), ("TROUBLE", "Problem"), ("TRUMPET", "Brass instrument"),
    ("TURNING", "Rotating"), ("UNIFORM", "Matching clothes"), ("UNKNOWN", "Not known"),
    ("UNUSUAL", "Rare"), ("UPGRADE", "Improve"), ("USUALLY", "Normally"),
    ("UTILITY", "Service"), ("VARIETY", "Assortment"), ("VENTURE", "Risky business"),
    ("VERSION", "Edition"), ("VETERAN", "Experienced one"), ("VILLAGE", "Small town"),
    ("VINTAGE", "Classic"), ("VISIBLE", "Can be seen"), ("VOLCANO", "Lava mountain"),
    ("WARRANT", "Authority"), ("WARRIOR", "Fighter"), ("WEATHER", "Climate"),
    ("WEBSITE", "Web page"), ("WEDDING", "Marriage"), ("WELCOME", "Greeting"),
    ("WESTERN", "Cowboy genre"), ("WHISPER", "Speak softly"), ("WHOEVER", "Any person"),
    ("WILDLIFE", "Wild animals"), ("WINNING", "Victorious"), ("WRITTEN", "On paper"),

    # ── 8-letter words ─────────────────────────────────
    ("ABSOLUTE", "Complete"), ("ABSTRACT", "Not concrete"), ("ACCIDENT", "Mishap"),
    ("ACCURATE", "Exact"), ("ACHIEVED", "Accomplished"), ("ACTIVITY", "Action"),
    ("ACTUALLY", "In fact"), ("ADDITION", "Extra part"), ("ADEQUATE", "Sufficient"),
    ("ADVANCED", "Ahead"), ("ADVISING", "Counseling"), ("ADVOCATE", "Supporter"),
    ("AIRPLANE", "Flying machine"), ("ALPHABET", "Letter set"), ("AMBITION", "Drive"),
    ("ANALYSIS", "Examination"), ("ANNOUNCE", "Declare"), ("ANYWHERE", "Any place"),
    ("APPARENT", "Obvious"), ("APPETITE", "Hunger"), ("APPLAUSE", "Clapping"),
    ("APPROACH", "Come near"), ("APPROVAL", "Consent"), ("BATHROOM", "Wash room"),
    ("BLANKETS", "Bed covers"), ("BOUNDARY", "Border"), ("BRACELET", "Wrist band"),
    ("BRANCHES", "Tree limbs"), ("BREAKING", "Snapping"), ("BRINGING", "Carrying"),
    ("BUILDING", "Structure"), ("BUSINESS", "Commerce"), ("CALENDAR", "Date tracker"),
    ("CAMPAIGN", "Drive"), ("CATEGORY", "Group"), ("CEREMONY", "Ritual"),
    ("CHAIRMAN", "Board leader"), ("CHAMPION", "Winner"), ("CHANGING", "Altering"),
    ("CHAPTERS", "Book parts"), ("CHEMICAL", "Substance"), ("CHILDREN", "Young ones"),
    ("CIRCULAR", "Round"), ("CIVILIAN", "Non-military"), ("CLIMBING", "Going up"),
    ("CLOTHING", "Garments"), ("COLONIAL", "Settlement era"), ("COMBINED", "Merged"),
    ("COMMERCE", "Trade"), ("COMMUNAL", "Shared"), ("COMPARED", "Contrasted"),
    ("COMPLETE", "Finished"), ("COMPOSED", "Calm"), ("COMPUTER", "Digital device"),
    ("CONCLUDE", "End"), ("CONCRETE", "Hard material"), ("CONFUSED", "Puzzled"),
    ("CONGRESS", "Lawmakers"), ("CONSIDER", "Think about"), ("CONSTANT", "Steady"),
    ("CONSUMER", "Buyer"), ("CONTINUE", "Go on"), ("CONTRACT", "Agreement"),
    ("CONTRAST", "Difference"), ("CONVINCE", "Persuade"), ("CORRIDOR", "Hallway"),
    ("CRIMINAL", "Lawbreaker"), ("CRITICAL", "Important"), ("CROSSING", "Intersection"),
    ("CULTURAL", "Of culture"), ("CUPBOARD", "Kitchen cabinet"), ("CUSTOMER", "Client"),
    ("DATABASE", "Info storage"), ("DAUGHTER", "Female child"), ("DECEMBER", "Last month"),
    ("DECISION", "Choice"), ("DECREASE", "Lessen"), ("DEFINITE", "Certain"),
    ("DELICATE", "Fragile"), ("DELIVERY", "Bringing"), ("DESIGNER", "Creator"),
    ("DIALOGUE", "Conversation"), ("DINOSAUR", "Extinct reptile"), ("DIPLOMAT", "Envoy"),
    ("DIRECTOR", "Leader"), ("DISCOUNT", "Price cut"), ("DISCOVER", "Find"),
    ("DISORDER", "Chaos"), ("DISTANCE", "Far away"), ("DISTRICT", "Area"),
    ("DIVIDEND", "Profit share"), ("DOMESTIC", "Home"), ("DOMINANT", "Ruling"),
    ("DOORSTEP", "Entrance"), ("DRAMATIC", "Theatrical"), ("DRIVEWAY", "Car path"),
    ("DROPPING", "Falling"), ("EARNINGS", "Income"), ("ECONOMIC", "Financial"),
    ("EDUCATOR", "Teacher"), ("EIGHTEEN", "After 17"), ("ELECTION", "Voting"),
    ("ELECTRIC", "Current"), ("ELEGANCE", "Grace"), ("ELEPHANT", "Huge animal"),
    ("ELEVATOR", "Lift"), ("EMERGING", "Coming out"), ("EMISSION", "Output"),
    ("EMPHASIS", "Stress"), ("EMPLOYEE", "Worker"), ("ENCLOSED", "Inside"),
    ("ENGAGING", "Interesting"), ("ENORMOUS", "Huge"), ("ENVELOPE", "Letter holder"),
    ("ENTIRELY", "Completely"), ("ENTRANCE", "Entry"),
    ("ESTIMATE", "Guess"), ("EVALUATE", "Assess"), ("EVIDENCE", "Proof"),
    ("EXACTING", "Demanding"), ("EXCHANGE", "Trade"), ("EXCITING", "Thrilling"),
    ("EXERCISE", "Workout"), ("EXQUISITE", "Beautiful"), ("EXTENDED", "Longer"),
    ("EXTERNAL", "Outside"), ("FABULOUS", "Wonderful"), ("FACILITY", "Building"),
    ("FAMILIAR", "Known"), ("FAVORITE", "Preferred"), ("FEATURES", "Traits"),
    ("FEEDBACK", "Response"), ("FESTIVAL", "Celebration"), ("FIGURING", "Solving"),
    ("FINISHED", "Done"), ("FLASHLIGHT", "Portable light"), ("FLEXIBLE", "Bendable"),
    ("FLOATING", "On water"), ("FOOTBALL", "Gridiron sport"), ("FORECAST", "Prediction"),
    ("FRAGMENT", "Piece"), ("GENERATE", "Create"), ("GENEROUS", "Giving"),
    ("GRADIENT", "Slope"), ("GRACEFUL", "Elegant"), ("GRADUATE", "Finish school"),
    ("GUARDIAN", "Protector"), ("GUIDANCE", "Direction"), ("HANDSOME", "Good-looking"),
    ("HANDLING", "Managing"), ("HAPPENED", "Occurred"), ("HEADLINE", "Top story"),
    ("HERITAGE", "Tradition"), ("HOMEWORK", "School work"), ("HONESTLY", "Truly"),
    ("HOSPITAL", "Medical center"), ("HUMOROUS", "Funny"), ("IDENTIFY", "Name"),
    ("IGNORANT", "Unaware"), ("IMAGINED", "Pictured"), ("INCIDENT", "Event"),
    ("INCREASE", "Grow"), ("INDICATE", "Show"), ("INFERIOR", "Lower"),
    ("INNOCENT", "Not guilty"), ("INSPIRED", "Motivated"), ("INSTANCE", "Example"),
    ("INTEREST", "Curiosity"), ("INTERNAL", "Inside"), ("ISOLATED", "Alone"),
    ("JUDGMENT", "Decision"), ("KEYBOARD", "Typing device"), ("KINDNESS", "Nice acts"),
    ("LAUNDRY", "Clothes wash"), ("LIFETIME", "Whole life"), ("LIGHTING", "Lamps"),
    ("LOCATION", "Place"), ("MAGNETIC", "Attracting"), ("MAINTAIN", "Keep up"),
    ("MAJORITY", "Most"), ("MANAGING", "Running"), ("MANIFEST", "Clear"),
    ("MARATHON", "Long race"), ("MARRIAGE", "Wedding"), ("MATERIAL", "Substance"),
    ("MEASURED", "Sized up"), ("MECHANIC", "Car fixer"), ("MEDICINE", "Health cure"),
    ("MEMORIAL", "Monument"), ("MERCHANT", "Trader"), ("MIDNIGHT", "12 AM"),
    ("MILITARY", "Armed forces"), ("MINIMIZE", "Reduce"), ("MODERATE", "Medium"),
    ("MOMENTUM", "Motion force"), ("MONOPOLY", "Board game"), ("MORTGAGE", "Home loan"),
    ("MOUNTAIN", "High peak"), ("MOVEMENT", "Motion"), ("MULTIPLE", "Many"),
    ("MUSHROOM", "Fungi food"), ("NATIONAL", "Of a nation"), ("NAVIGATE", "Steer"),
    ("NEGATIVE", "Less than zero"), ("NEIGHBOR", "Next door"), ("NINETEEN", "After 18"),
    ("NOTEBOOK", "Writing pad"), ("NUMEROUS", "Many"), ("OBSTACLE", "Barrier"),
    ("OCCASION", "Event"), ("OFFERING", "Gift"), ("OFFICIAL", "Formal"),
    ("OPPOSITE", "Contrary"), ("OPTIONAL", "Not required"), ("ORDINARY", "Normal"),
    ("ORIGINAL", "First"), ("OVERCOME", "Beat"), ("PAINTING", "Art work"),
    ("PARALLEL", "Side by side"), ("PASSPORT", "Travel document"), ("PATIENCE", "Calm waiting"),
    ("PEACEFUL", "Calm"), ("PECULIAR", "Odd"), ("PERSONAL", "Private"),
    ("PHYSICAL", "Bodily"), ("PLATFORM", "Stage"), ("PLEASANT", "Nice"),
    ("PLEASURE", "Joy"), ("PLENTIFUL", "Abundant"), ("POSITIVE", "Good"),
    ("POSSIBLE", "Can be done"), ("POWERFUL", "Strong"), ("PRACTICE", "Rehearse"),
    ("PRECIOUS", "Valuable"), ("PREPARED", "Ready"), ("PRESERVE", "Keep safe"),
    ("PRESSURE", "Force"), ("PRINCESS", "Royal daughter"), ("PRIORITY", "Top concern"),
    ("PROBABLY", "Likely"), ("PROCEEDS", "Profits"), ("PRODUCER", "Maker"),
    ("PROFOUND", "Deep"), ("PROGRESS", "Advance"), ("PROMISED", "Vowed"),
    ("PROMPTLY", "Quickly"), ("PROPERLY", "Correctly"), ("PROPERTY", "Real estate"),
    ("PROPOSAL", "Suggestion"), ("PROSPECT", "Outlook"), ("PROVIDED", "Gave"),
    ("PROVINCE", "Region"), ("PURCHASE", "Buy"), ("PURSUING", "Chasing"),
    ("QUESTION", "Query"), ("REACTION", "Response"), ("RECEIVED", "Got"),
    ("RECYCLED", "Reused"), ("REDUCING", "Lessening"), ("REGIONAL", "Local"),
    ("RELATION", "Connection"), ("RELEASED", "Let go"), ("RELIABLE", "Dependable"),
    ("RELIGION", "Faith"), ("REMEMBER", "Recall"), ("RENOWNED", "Famous"),
    ("REPEATED", "Done again"), ("REPORTED", "Told"), ("REQUIRED", "Needed"),
    ("RESEARCH", "Study"), ("RESIDENT", "Dweller"), ("RESOURCE", "Asset"),
    ("RESPONSE", "Reply"), ("RESTLESS", "Uneasy"), ("REVIEWER", "Critic"),
    ("RIGOROUS", "Strict"), ("ROMANTIC", "Loving"), ("ROOFTOPS", "House tops"),
    ("SANDWICH", "Bread meal"), ("SCENARIO", "Situation"), ("SCHEDULE", "Timetable"),
    ("SCISSORS", "Cutting tool"), ("SCORPION", "Desert creature"), ("SCULPTOR", "Stone artist"),
    ("SEASONAL", "Periodic"), ("SECURITY", "Safety"), ("SEMESTER", "School term"),
    ("SENTENCE", "Paragraph unit"), ("SEQUENCE", "Order"), ("SERGEANT", "Army rank"),
    ("SHIPPING", "Mail delivery"), ("SHORTAGE", "Deficit"), ("SHOULDER", "Body joint"),
    ("SILENTLY", "Quietly"), ("SKELETAL", "Bone-like"), ("SLEEPING", "Resting"),
    ("SLIGHTLY", "A little"), ("SMOOTHLY", "Without bumps"), ("SNAPSHOT", "Quick photo"),
    ("SOMEBODY", "Some person"), ("SOMEWHAT", "A little"), ("SOUTHERN", "From the south"),
    ("SPECIFIC", "Particular"), ("SPECTRAL", "Ghost-like"), ("SPLENDID", "Magnificent"),
    ("STANDARD", "Normal"), ("STANDING", "Upright"), ("STARFISH", "Sea creature"),
    ("STARTING", "Beginning"), ("STICKING", "Adhering"), ("STIRRING", "Moving"),
    ("STOPPING", "Halting"), ("STRAIGHT", "Not curved"), ("STRANGER", "Unknown person"),
    ("STRATEGY", "Plan"), ("STRENGTH", "Power"), ("STRICTLY", "Firmly"),
    ("STRUGGLE", "Fight"), ("STUNNING", "Beautiful"), ("SUBTITLE", "Caption"),
    ("SUBURBAN", "Near city"), ("SUDDENLY", "Without warning"), ("SUITABLE", "Fitting"),
    ("SUPERIOR", "Better"), ("SUPPOSED", "Assumed"), ("SURPRISE", "Shock"),
    ("SURROUND", "Encircle"), ("SURVIVAL", "Living on"), ("SUSPENSE", "Tension"),
    ("SWEEPING", "Wide"), ("SWIMMING", "Pool sport"), ("SYMPATHY", "Compassion"),
    ("TEACHING", "Educating"), ("TERMINAL", "End point"), ("TERRIFIC", "Great"),
    ("THINKING", "Pondering"), ("THIRTEEN", "After twelve"), ("THOUSAND", "1000"),
    ("TOGETHER", "As one"), ("TOMORROW", "Next day"), ("TOUCHING", "Moving"),
    ("TRAILING", "Following"), ("TRAINING", "Teaching"), ("TRANSFER", "Move"),
    ("TREASURE", "Riches"), ("TRILLION", "Huge sum"), ("TROPICAL", "Hot climate"),
    ("TRUSTING", "Having faith"), ("UMBRELLA", "Rain shield"), ("UNCOMMON", "Rare"),
    ("UNDERDOG", "Unlikely winner"), ("UNIVERSE", "All there is"), ("UNLIKELY", "Doubtful"),
    ("UNWORTHY", "Not deserving"), ("VACATION", "Time off"), ("VALIDATE", "Confirm"),
    ("VALUABLE", "Precious"), ("VARIABLE", "Changeable"), ("VENTURES", "Risky projects"),
    ("VERTICAL", "Upright"), ("VIOLENCE", "Force"), ("WORKSHOP", "Skill class"),
    ("YEARBOOK", "School album"),
]


def get_word_bank() -> dict[str, str]:
    """Return {WORD: clue} dictionary."""
    return {word: clue for word, clue in _RAW}


def get_words_by_length() -> dict[int, list[tuple[str, str]]]:
    """Return {length: [(word, clue), ...]} grouped by word length."""
    result: dict[int, list[tuple[str, str]]] = {}
    for word, clue in _RAW:
        result.setdefault(len(word), []).append((word, clue))
    return result
